### ISSUE TITLE
bump to 1.0.0 for semver support

### ISSUE THREAD

**Issue by dylang** [depcheck/depcheck#131]
Not a bug, just a friendly request. :smile:

By bumping to `1.0.0` it means _minor_ and _patch_ releases are backwards compatible and projects that depend on `depcheck` like [npm-check](https://github.com/dylang/npm-check) can easily upgrade. 

If you think the API is not stable enough for a `1.0.0` I still wouldn't worry. I personally don't mind frequent major bumps - it tells me the API is evolving and that's great too. Browserify is on [version 13.x.y](https://github.com/substack/node-browserify/blob/master/package.json#L3).

On a totally different note, I just noticed the release notes with each deploy, thank you for taking the time to do this! I wish I could be as disciplined.

**Comment by lijunle** [comment]
I could seriously consider this. However, I am planning a big API and CLI change on 0.7.x.

The returned result object is suggested to name as `unused` and access as `unused.dependencies` and `unuser.devDependencies`. This is OK until we introduced the feature to find out the missing dependency and dependency usage - the access `unused.missing` does make sense.

Proposal: access via `result.unusedDependencirs`, `result.unusedDevDependencies`, `result.missingDependencies` and `result.usedDependencirs`.

**Comment by johanneserber** [comment]
👍  all npm published packages should start from 1.0.0, not from 0.x.x

**Comment by VincentLanglet** [comment]
It should be time to bump a major version

**Comment by rumpl** [comment]
Next one then, I wanted to add a bunch of stuff before going 1.0 but I guess after 6 years we can say that it is time
