### ISSUE TITLE
False positivies on app-module-path

### ISSUE THREAD

**Issue by nfantone** [depcheck/depcheck#132]
While using [app-module-path](https://www.npmjs.com/package/app-module-path), every `require`d module affected by that is reported as a "missing dependency".

``` sh
Missing dependencies
* logger
* config
* services
* lodash
```

Here, `logger` and `config` are  actually located under an `./app` directory, but the relative path can be  omitted thanks to:

``` javascript
require('app-module-path').addPath(__dirname + '/app');
```

being present at the beginning of the main script. Moreover, `services` is not even a module. The actual requirements comes from:

``` javascript
const seneca = require('services/seneca');
```

Can't say why _depcheck_ reports it that way.

**Comment by lijunle** [comment]
Some bullets:

1. This package does something really bad - it changes the node.js built-in behavior.
2. Its feature looks good. I am not sure what happen on published module - it does not load `node_modules`
3. I could like to support it in depcheck.
4. It is very hard to support it. The current design is not good to handle this case.
5. I added it to backlog and will think about how to support the `app-module-path` loaded modules.

---

Is the `lodash` in your list in the same case?

**Comment by nfantone** [comment]
@lijunle 

> This package does something really bad - it changes the node.js built-in behavior.

Depends on what you consider "bad". I think it's awesome. Nevermore those `'../../../../middlewares/stack/chain` things on your imports.

> I added it to backlog and will think about how to support the app-module-path loaded modules.

Great news! Thank you very much for your support.

**Comment by lijunle** [comment]
@nfantone Is the lodash in your list in the same case?

**Comment by nfantone** [comment]
No, it's not. Lodas was an actual miss. So, +1 for depcheck.

**Comment by lijunle** [comment]
Aha, glad to see the tool is helping you. :)

**Comment by ericelliott** [comment]
FYI, it's reporting false positives for modules in `NODE_PATH`, too.

**Comment by lijunle** [comment]
@ericelliott could you please open a new issue to details the information? Thank you!

**Comment by vjpr** [comment]
For this to work currently you would need to add all the modules inside your NODE_PATH dirs to `ignoreMatches`.

**Comment by mrchief** [comment]
> This package does something really bad - it changes the node.js built-in behavior.

I agree with @lijunle on this one. The extra dots are simple and intuitive. `app-module-path` not only alter default behaviors and thus breaking any tool chain that rely on default behavior, but it also open up the possibility of abuse and violates the principle of least surprise. 

I'd actually vote for not supporting it. If possible, make the support for non-standard things available via plugins. People can opt-in if they choose to do so.
