### ISSUE TITLE
[Request] Integrate npmsearch.com scores

### ISSUE THREAD

**Issue by petermikitsh** [depcheck/depcheck#134]
It would be nice to provide the npmsearch.com score, or rather, a warning for a specific module if the score is low.

As a developer, I want to be sure I am using projects that are well tested, that way I can be confident in depending on a module.

Ideally the developer should vet each module they use, but on existing projects it's considerable work to analyze all of your modules for quality.

**Comment by lijunle** [comment]
@petermikitsh 

Sorry, I don't think that is in the scope of this package. This tool is only to provide the dependency usage information for user. 

I tried npmsearch.com, I think those functions should be check BEFORE install a package. However, depcheck and npm-check are for action AFTER install packages. A better interface to check available packages is web pages.

The score in npmsearch.com is interesting. However, there are more concerns to decide which one I should choose:

- Number of stars.
- Number of download per day/week/month
- What else?

I could like to see a web interface to integrate such information and provide it to me. That could be useful. 

Thanks!
