### ISSUE TITLE
Add browserify transforms/plugins

### ISSUE THREAD

**Issue by Calvein** [depcheck/depcheck#135]
As said in [this issue in npm-check](https://github.com/dylang/npm-check/issues/100), depcheck doesn't check for browserify transforms or plugins (I'll just talk about transforms for now) when they are passed as strings. 
Browserify's documentation defines transform like this:

> ## b.transform(tr, opts={})
> 
> If `tr` is a function, it will be called with `tr(file)` and it should return a
> [through-stream](https://github.com/substack/stream-handbook#through)
> that takes the raw file contents and produces the transformed source.
> 
> If `tr` is a string, it should be a module name or file path of a
> [transform module](https://github.com/substack/module-deps#transforms)
> with a signature of:
> 
> ``` js
> var through = require('through');
> module.exports = function (file) { return through() };
> ```

It basically means that:

``` js
import mytransformify from 'mytransformify'
browserify('index.js').transform(mytransformify)
```

Is the same as:

``` js
browserify('index.js').transform('mytransformify')
```

The first example will works because it explicitly import `mytransformify`, but the second won't because it's implicit.

**Comment by lijunle** [comment]
Hi, @Calvein 

Thanks for reporting this. I get your ideas now. This is do-able. I ever did something similar for `gulp-load-plugins`. However, the implementation is tricky. I want a better way to solve the problem. I could like to add it to backlog.

Reference: https://github.com/substack/node-browserify#btransformtr-opts
