### ISSUE TITLE
Exit code from `depcheck` executable

### ISSUE THREAD

**Issue by domharrington** [depcheck/depcheck#140]
Using the `depcheck` executable should exit with an error code if there are unused dependencies. Running it on my project this doesnt appear to be the case.

```bash
$ depcheck
Unused devDependencies
* gulp-eslint
* should-http
Missing dependencies
* mongoose-text-search
```

Results in an exit code:

```bash
$ echo $?
0
```

Versions:
Node: v5.7.0
depcheck: 0.6.3.

I've had a look around in the code and the issue appears to stem from this block of code:
https://github.com/depcheck/depcheck/blob/6cb92533adf3ed2ed3f6054d6cb3c51e56731615/bin/depcheck#L11-L13
If you move the `process.exit` to outside of the `on('finish')` callback then it works as expected. Have you seen this issue before? What was the reasoning behind adding that callback?

**Edit**:
This was introduced here: https://github.com/depcheck/depcheck/commit/44124dd908efb5b638b1d417ece5e2aa7a2daa50

Checking out the version before the 0.6.0 release (0.5.11) has fixed the issue.

**Edit 2**:
I've added a regression test for this issue in my fork:
https://github.com/domharrington/depcheck/commit/99e6ce1816e9e457a7366b969551472f355991b0
Any help would be appreciated!

**Edit 3**:
According to the node docs, `process.stdout` never emits a finish event: https://nodejs.org/api/process.html#process_process_stdout. Can confirm this is the case as when i put a log statement into that callback, it never gets called.

**Comment by lijunle** [comment]
Hi, @domharrington thanks for your awesome investigation! I will take a look on your code later.

@gtanner, do you have any ideas about this?

**Comment by iamstarkov** [comment]
@lijunle i guess it can be fixed by using `process.exitCode = 1;`

**Comment by domharrington** [comment]
I'm not sure that it can... because the callback [https://github.com/depcheck/depcheck/blob/6cb92533adf3ed2ed3f6054d6cb3c51e56731615/bin/depcheck#L12]() never gets called. We can just remove this callback, but then i'm not sure what issues this was causing in #98

**Comment by iamstarkov** [comment]
we can remove this callback all together, and just set `process.exitCode = 1` in the cli if there is [anything unused](https://github.com/depcheck/depcheck/blob/master/src/cli.js#L118) or [in case of error](https://github.com/depcheck/depcheck/blob/master/src/cli.js#L121)

**Comment by iamstarkov** [comment]
are there any tests covering required behaviour?

**Comment by lijunle** [comment]
I saw [this](https://github.com/dylang/npm-check/pull/150) pork request to do similar thing in npm-check. It looks like we can do the same thing here.

@iamstarkov Yes, there will be treat case cover the exit code. But I think the test codes need to update too, if we are going to remove the process.exit call.

**Comment by lijunle** [comment]
And, for @domharrington 's requirement, check the *update 2* from the first post. That test is very nice, should be cherry picked to here. :)

**Comment by lijunle** [comment]
Found this package and it will handle the stdout for us: https://www.npmjs.com/package/exit

**Comment by lijunle** [comment]
Fixed with the awesome `process.exitCode`. Thank you, all! :clap:

**Comment by iamstarkov** [comment]
cool

**Comment by pdehaan** [comment]
Any chance we get get a new release published to npm with this fix?

**Comment by gflarity** [comment]
Publish please :)

**Comment by domharrington** [comment]
Can you publish a new version to npm?

**Comment by lijunle** [comment]
@domharrington The version 0.6.4 should include this fix. Could you please test it?

**Comment by PatrickEickmeier** [comment]
HI @lijunle I use version 0.6.7 and it doesn't work for me.

**Comment by PatrickEickmeier** [comment]
I made some tests and it seems that there is only an exit code >0 when there are unused dependencies.

```
$ depcheck --ignores=winston
Missing dependencies
* handlebars
$ echo $?
0
```

```
$ depcheck --ignores=handlebars
Unused dependencies
* winston
$ echo $?
255
```
