### ISSUE TITLE
False missing alert for webpack aliases.

### ISSUE THREAD

**Issue by Zerim** [depcheck/depcheck#144]
Our project heavily uses [webpack aliases](https://webpack.github.io/docs/configuration.html#resolve-alias), so we have many imports/requires that refer to modules that are not explicitly listed in our package.json.

Ideally these would not be alerted as missing modules.

**Comment by evenfrost** [comment]
Doubling this. Using
```js
resolve: {
  root: resolve(__dirname, 'client')
}
```
in my webpack config, and all assets under 'client' folder, when required as
```js
import smth from 'assets/smth'
```
are shown as `missing`.

**Comment by swearer23** [comment]
```
var webpackAliasDetect = function(node , deps){
if(node.type === 'ImportDeclaration' && node.source && node.source.value){
         if(node.source.value.match(/^(components|actions|reducers)/)){
             return ['src/' + node.source.value];
         }
     }
     return [];
}
```

don't know if it would be helpful

but you could resolve this issue by adding a custom detector like above

and add it to your depcheck options.

**Comment by dan-lee** [comment]
Thanks to @swearer23!
As it didn't work right away I had to tweak it.
Here's my result, for anyone concerned:

```js
const resolveAliases = require('./webpack.config')
const detectors = [depcheck.detector.requireCallExpression]

if (resolveAliases) {
  const webpackAliasDetect = node => {
    if (node.type === 'ImportDeclaration' && node.source && node.source.value) {
      for (let key in resolveAliases) {
        if (node.source.value.startsWith(key)) {
          return [path.join(resolveAliases, key) + node.source.value]
        }
      }
      return [node.source.value]
    }
    return []
  }
 detectors.push(webpackAliasDetect)
} else {
 detectors.push(depcheck.detector.importDeclaration)
}
```

**Comment by rumpl** [comment]
not stale

**Comment by thopiddock** [comment]
not stale

**Comment by thopiddock** [comment]
Still would be nice to know if there's inbuilt support for this as I'm having the same issues as previous commenters
.

**Comment by rumpl** [comment]
PRs welcome
