### ISSUE TITLE
False positive when requiring files from modules directly:

### ISSUE THREAD

**Issue by SimonSchick** [depcheck/depcheck#147]
Assume there is a module called `@org/my-module` installed but it's never required as `require('@org/my-module')` but instead only submodules are loaded such as `require('@org/my-module/my-sub-module')`.
depcheck does not pick those up and instead flags them as unused.
This should be relatively easy to fix.

**Comment by lijunle** [comment]
This should be handled. We are using [require-package-name](https://www.npmjs.com/package/require-package-name) to handle this.

Could you detail your case? Which package is reported? Hope does it be used?

**Comment by SimonSchick** [comment]
The problem seems to be non deterministic.
It appears that it only shows these false positives every few runs.

**Comment by lijunle** [comment]
@SimonSchick I looks strange, do you still get into this problem? Could you please provide more details about it?
