### ISSUE TITLE
Support ESLint YAML and JS config.

### ISSUE THREAD

**Issue by lijunle** [depcheck/depcheck#150]
Document: http://eslint.org/docs/user-guide/configuring#configuration-file-formats

**Comment by goloroden** [comment]
This is implemented by https://github.com/depcheck/depcheck/pull/173

**Comment by marcjordan** [comment]
I don't believe #173 is opening and reading 'package.json' as one of the allowed filenames. Can we get this or #154 re-opened?

**Comment by lijunle** [comment]
Re-opened.

Hey, @marcjordan I am sorry that, I really don't have time to continue working on this project. If you are interested in fixing these issue, please tell me and I will loop you as contributors.

**Comment by VincentLanglet** [comment]
@rumpl This can be closed c.f. https://github.com/depcheck/depcheck/blob/master/src/special/eslint.js
