### ISSUE TITLE
ES7 babylon plugins wildcard not working 

### ISSUE THREAD

**Issue by vjpr** [depcheck/depcheck#153]
https://github.com/depcheck/depcheck/blob/master/src/parser/es7.js#L9

The plugins wildcard here is not working for me...at least not for `flow`. I could not see it documented in the Babylon library either.

**Comment by lijunle** [comment]
It is defined here: https://github.com/babel/babylon/blob/8b150813f5a534e4279df25c41c37cc9dd860ebe/src/parser/index.js#L26

It is a undocumented feature.

**Comment by vjpr** [comment]
Ok looks like a bug in Babylon. There is code to make `flow` run last when passed in as a plugin. This special case doesn't work when only passing in a wildcard.

**Comment by vjpr** [comment]
Closing in favor of https://github.com/babel/babylon/issues/43

**Comment by lijunle** [comment]
@vjpr Actually, I am not sure how the special code is affecting the wildcard. It looks good to me. For other logic, the `jsx` and `flow` looks similar situation. I am not clear why flow not works.

**Comment by lijunle** [comment]
It might a bug from out side. I looked the [jsx.js](https://github.com/depcheck/depcheck/blob/master/src/parser/jsx.js#L9) is using `plugins: ['*', 'jsx']`.

**Comment by lijunle** [comment]
@vjpr Could you please add a regression test and list `flow` and `jsx` besides the wildcard?

**Comment by vjpr** [comment]
I'll have to find some time later to dive in further and regression test it.

Babylon `plugins` is `*` when using `depcheck.parser.es7`, but when I replace it with my own function that is identical...`plugins` reports correctly. Both are using the same root level `babylon` dep too. Maybe its some sort of Babel caching on my end.
