### ISSUE TITLE
Support (package.json).eslintConfig.extends for `special.eslint`

### ISSUE THREAD

**Issue by vjpr** [depcheck/depcheck#154]
http://eslint.org/docs/user-guide/configuring

**Comment by lijunle** [comment]
Hi, @vjpr Are you referring to **this** support?

> Configuration Files - use a JavaScript, JSON or YAML file to specify configuration information for an entire directory and all of its subdirectories. This can be in the form of an .eslintrc.* file or **an eslintConfig field in a package.json file**, both of which ESLint will look for and read automatically, or you can specify a configuration file on the command line.

**Comment by vjpr** [comment]
Yep. Just saw https://github.com/depcheck/depcheck/issues/150 which looks like it covers it.

**Comment by lijunle** [comment]
I could make sure u understand you requirement. Are you writing the eslint config in the package.json file?

**Comment by vjpr** [comment]
Yep.

```
function depcheckSpecialEslintPackageJson(content, filePath) {
  const filename = path.basename(filePath)
  if (filename === 'package.json') {
    const {eslintConfig} = JSON.parse(content)
    // TODO(vjpr): Use `special.eslint`'s built-in `extends` handling...
    if (eslintConfig.extends) {
      return ['eslint-config-' + eslintConfig.extends]
    }
  }
  return []
}
```

**Comment by lijunle** [comment]
@vjpr Could you like to make some changes to [eslint.js](https://github.com/depcheck/depcheck/blob/master/src/special/eslint.js#L90) to get package.json support? I think the most logic for `.eslintrc` can be reused for your case.

**Comment by goloroden** [comment]
This is implemented by https://github.com/depcheck/depcheck/pull/173

**Comment by marcjordan** [comment]
Are we sure this was fixed? If I remove my .eslintrc file it doesn't appear to be looking at the config in package.json.
