### ISSUE TITLE
Cannot scan large project

### ISSUE THREAD

**Issue by jaredmcateer** [depcheck/depcheck#159]
I am working on a large webapp (1200+ files) that I want to check for unused dependencies however depcheck kept reporting a whole bunch of false positives that when I manually checked most of them were definitely used.

I noticed that you get more verbose output if you format the results as json so I did that and I found that a large number of files in the `invalidDirs` section had the error:

`Error: EMFILE: too many open files'

As a test I tried dropping in `graceful-fs` where `fs` was used and the number of errors were reduced significantly but not completely.

**Comment by lijunle** [comment]
Hi, @jaredmcateer

Thanks for trying it in a big project. Are you changing every `fs` to `graceful-fs`? What false positive do you find?
