### ISSUE TITLE
Support for coffee?

### ISSUE THREAD

**Issue by braco** [depcheck/depcheck#16]
How difficult would it be to add coffee-script support so that the "unused" checks are accurate in coffee projects?

**Comment by PavelKonon** [comment]
+1

**Comment by kylemac** [comment]
+1

**Comment by rahatarmanahmed** [comment]
+1

**Comment by ensonic** [comment]
+1

**Comment by alinex** [comment]
+1

**Comment by Wilfredfury** [comment]
+1

**Comment by mathieudutour** [comment]
Support for coffeeScript has just landed in [depcheck-es6](https://github.com/lijunle/depcheck-es6)

See [the comment from lijunle](https://github.com/rumpl/depcheck/issues/21#issuecomment-141687991).

**Comment by lijunle** [comment]
Thanks for @mathieudutour 's PR. Those codes finally come back to the original depcheck. I have released version 0.5.9 to [depcheck package](https://www.npmjs.com/package/depcheck) in NPM to include CoffeeScript support.

Please enjoy it. Open issue here if get any problem.
