### ISSUE TITLE
Improvements for CI use

### ISSUE THREAD

**Issue by mcasimir** [depcheck/depcheck#162]
We use depcheck in our CI to prevent devs from commiting unused deps

Due to ignored deps and false positives it is not currently possible to just say `depcheck .`

I see 3 major issues there:
1. fail on unsuccessful execution
2. support `.depcheckignore`, `.depcheckrc` or `package.json` section
3. allows to skip missing dependencies (its more likely that those are covered by tests so it just reports false positives)

Sorry to report this without spending much time in reading guidelines and checking for dupes but i have no time now.

Please accept my apologies if what i said was already known or addressed.

Thanks

**Comment by ChrisPearce** [comment]
A .depcheckrc file would be very useful for automated builds

**Comment by mcasimir** [comment]
I've ended up wrapping it https://github.com/mcasimir/depcheck-ci

 But i'd really like to see those features in depcheck itself.

**Comment by rumpl** [comment]
not stale

**Comment by znarf** [comment]
`.depcheckrc` is supported since https://github.com/depcheck/depcheck/pull/408

**Comment by znarf** [comment]
Are 1) and 3) talent care of?

**Comment by rumpl** [comment]
* 1 yes
* 3 no and to be honest I don't wanna
