### ISSUE TITLE
Add support for @types declaration packages

### ISSUE THREAD

**Issue by ChrisPearce** [depcheck/depcheck#163]
Typescript v2 is moving to support a new approach to adding typings to a project.

Type definitions will be included in packages contained within the @types scope (e.g. @types/mypackage), which can simply be installed via npm (just like other packages).

More information can be found at:
https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

Currently any of these @types packages that are referenced in package.json, are incorrectly recognised as unused dependencies.

**Comment by lijunle** [comment]
Good feature!

Do you want to ignore all the @types packages? Or only the ones on use?

**Comment by ChrisPearce** [comment]
Ideally, it would be great to recognise the ones that are used, but if that doesn't prove possible it would be great to have an option that just ignores all @types scoped packaged.

**Comment by ChrisPearce** [comment]
As a workaround, I'm currently using the following command to ignore all @types scoped packages:
`depcheck --ignores @types/*`

**Comment by GongT** [comment]
with typescript project, `@types` packages can be "used" with 3 different:

2 way in source code, that's simple to parse:
```ts
///<reference types="node"/>
import React from 'react';
import someThing from '@scoped/package'; // <- "@types/scoped__package"
```

another in `tsconfig.json`, but is complicated.    
[tsconfig.json document](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html)
( see section `@types, typeRoots and types`)

for each tsconfig found in project:
1. can be renamed to everything. it's just a JSON, no field is required. (And also can add extra fields you want)
1. can `extend` another one. every file on the chain can use as the final one.
1. once a tsconfig file result contains `typeRoots`, but "*bla/bla/*node_modules/@types" not included, then this file is nothing to do with @types.
1. if there is no `typeRoots` nor `types`, all @types package can mark as used. no other detection is needed in entire project.
1. if there is `types` field, only listed package used by this file.

("typeRoots" and "types" is sub field of "compilerOptions")

**Comment by GongT** [comment]
BTW, `@types` package should not appear in dependencies, but should always in devDependencies.      
except some **extreme** rear situation.

**Comment by GongT** [comment]
Oh, When I start to write some code, I found that, the first 2 ways is also affected by tsconfig.json.    
It's really hard to do a "complete" check....    
I think this big job worth to create a new tool...

**Comment by mnkhouri** [comment]
@GongT thanks for the research, that does make it seem quite complex to properly detect `@types` usages with one or more `tsconfig.json` in the project. Instead of trying to analyze it ourselves, I wonder if there might be some way to extract this information from the typescript compiler? I haven't done a lot of research, but some documentation is [here](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#traversing-the-ast-with-a-little-linter).

**Comment by GongT** [comment]
I have not look into depcheck's `parser`, current `parseTypescript` not load user's `tsconfig.json`, this need first update. 

`ts.transpile` cannot used to analyze a "program", `types` option is hard code to `undefined`.

here is a simple script to list all files used when compile a project:
https://gist.github.com/GongT/1d5113a2ffd8ac7cac53123af61039d1

**Comment by conartist6** [comment]
I've opened a PR that would fix this. If people here could chip in a review perhaps it would speed the process of getting it shipped.

**Comment by ljharb** [comment]
This still doesn't seem solved - i'm still getting unused warnings for DT packages.

**Comment by SiRocke** [comment]
I've also made it to this point. Doing some major cleanup and it looks to still be an issue.

**Comment by ljharb** [comment]
The point of DT types is that you import them from the non-DT package name.
