### ISSUE TITLE
better --ignores documentation

### ISSUE THREAD

**Issue by gregglind** [depcheck/depcheck#164]
Perhaps I am not clear on what `--ignores` is for, or how to use it.  

In my example below, I want to tell it to silence everything about missing the `sdk` module [1].

```
$ depcheck --ignores=sdk . --json | json missing
{
  "sdk": [
    "/Users/glind/someproject/lib/somefile.js",
  ]
}
```

[1] `sdk` is included by the loader by default in Firefox addons.

**Comment by lijunle** [comment]
I think you want `--ignore-dirs` parameter.

**Comment by mnkhouri** [comment]
The Readme seems in pretty good shape right now, most likely it has been updated since this issue was opened -- please feel free to open a new issue if there are any more suggestions!
