### ISSUE TITLE
False negative for imported css

### ISSUE THREAD

**Issue by rojobuffalo** [depcheck/depcheck#168]
I'm getting an unused dependency result for a CSS module that is actually being used.

The module gets imported inside another css file.
### `styles/base.css`

```
@import 'sanitize.css/sanitize.css';
```

**Comment by lijunle** [comment]
Hi, @rojobuffalo I suppose you are writing Sass code. Depcheck assume the Sass code is having extension `.sass` or `.scss` instead of `.css`.

**Comment by rojobuffalo** [comment]
Hey @lijunle. Actually this is just plain CSS-Modules.
