### ISSUE TITLE
unused dependency "querystring" : false positive

### ISSUE THREAD

**Issue by mpacary** [depcheck/depcheck#170]
In a new directory, using :

**package.json**

```
{
  "name": "tests-deps",
  "main": "index.js",
  "description": "qsdf",
  "version": "1.0.0",
  "licence": {
    "license": "qsdf"
  },
  "private": true,
  "dependencies": {
    "handlebars": "^4.0.5",
    "querystring": "^0.2.0",
    "request": "^2.75.0",
    "xml2js": "^0.4.17"
  }
}
```

**index.js**

```
var hb = require('handlebars');
var qs = require('querystring');
var r = require('request');
```

Running `depcheck`, I get

```
Unused dependencies
* querystring  <--- false positive ?
* xml2js       <--- Ok, expected
```

`node -v` => v4.6.0
`npm -v` => 3.10.8
`depcheck --version` => 0.6.4

Ran this using babun/cygwin on a Windows 10 machine.

**Comment by lijunle** [comment]
@Frosty-Z Did you resolve the problem? What is the output of `depcheck --json`?

**Comment by Frosty-Z** [comment]
Still same issue with depcheck 0.6.7.

`depcheck --json` output is :
```
{
   "dependencies":[
      "querystring",
      "xml2js"
   ],
   "devDependencies":[

   ],
   "missing":{

   },
   "using":{
      "handlebars":[
         "C:\\Users\\Maxime\\...\\tests-deps\\index.js"
      ],
      "request":[
         "C:\\Users\\Maxime\\...\\tests-deps\\index.js"
      ]
   },
   "invalidFiles":{

   },
   "invalidDirs":{

   }
}

```

**Comment by rumpl** [comment]
Hey,

This is actually not a bug, `depcheck` excludes NodeJs core modules and [querystring](https://nodejs.org/api/querystring.html) is one of them.

**Comment by mpacary** [comment]
So shouldn't the output be like this?
```
Unused dependencies
  * xml2js

Ignored dependencies (Node.js core modules)
  * querystring
```

**Comment by rumpl** [comment]
I created a feature request for this one #308 

@mpacary Would you like to work on this one?

**Comment by mpacary** [comment]
Would be a good experience for me, but I have not enough time currently :-/
Maybe in a few weeks, I could create a PR.
