### ISSUE TITLE
depcheck not triggering fail from bashscript-

### ISSUE THREAD

**Issue by SameerSiddiqui** [depcheck/depcheck#171]
I have a bashscript which executes git/grunt commands automatically, checks for outdated packages and updates/publishes/deploys the app on npm and git.

i want to introduce depcheck in my script so i did the following.

```
depcheck --ignores '@cv/package1, package2, package3, @cv/package4'
                    if [ $? -eq 0 ]; then 
                                              #i go forward with my publish-
                        echo "Step-11: Checking Command to execute" 
                    else 
                     echo "Missing Dependencies found. Fix the package.json file and execute this script again."
                        exit 3
                    fi
```

But bash is not detecting if depcheck command has failed.  if i assign the depcheck command to variable i do get result but why isn't bash detecting it automatically with $? -eq 0 i have many grunt commands like jshint- and i check them with if [ $? -eq 0 ]; and it works.

Am i doing something wrong or this feature is not available with depcheck ?

**Comment by fastcodejava** [comment]
Yeah, seems like an valid issue.

**Comment by lijunle** [comment]
@SameerSiddiqui Did you resolve your problem? It sounds like not a problem from depcheck side.

**Comment by mnkhouri** [comment]
I'm unable to reproduce this today -- please feel free to reopen an issue if you continue to see this!

**Comment by spiray** [comment]
@mnkhouri This still doesn't work for me. This is my script -
```sh
#!/bin/bash

npx depcheck
if [[ $? == 1 ]]; then
    exit 1
else
    echo "All of the dependencies are up to date!!!"
fi
```
And this is the output - 
```
Unused dependencies
* exponentiation
Unused devDependencies
* @commitlint/config-conventional
* commitlint
* husky
* mysql
All of the dependencies are up to date!!!
```
Any ideas?

**Comment by rumpl** [comment]
The error code is not 1 but 255 (-1)

**Comment by spiray** [comment]
@rumpl thanks for the quick response, that doesn't seem to be the case, to simplify it, when I run 
```sh
npx depcheck
echo $?
```
I get - 
```
Unused dependencies
* exponentiation
Unused devDependencies
* @commitlint/config-conventional
* commitlint
* husky
* mysql
0
```

**Comment by rumpl** [comment]
Just did the same:
```
➜  front git:(master) ✗ cat test.sh 
#!/bin/bash

npx depcheck
echo $?
➜  front git:(master) ✗ ./test.sh 
Missing dependencies
* eslint-config-react-app
* babel-eslint
* eslint-plugin-import
* eslint-plugin-flowtype
* eslint-plugin-jsx-a11y
* eslint-plugin-react
* eslint-plugin-react-hooks
255
```

**Comment by spiray** [comment]
You have missing dependencies, maybe that is why. Can you test it again where you only have unused deps?

**Comment by rumpl** [comment]
```
➜  test ./test.sh 
Unused dependencies
* colors
255
```

**Comment by rumpl** [comment]
```
➜  test ./test.sh                     
Unused dependencies
* colors
Unused devDependencies
* request
255
```

No idea why it's 0 for you...

**Comment by spiray** [comment]
Hmm, I'll play around with it a little more

**Comment by rumpl** [comment]
Please do write here what you find, would like to know

**Comment by spiray** [comment]
@rumpl I figured out what the issue is, I was using Git Bash for windows. I had a colleague run the same script on MacOs and he got the 255. Thanks!

**Comment by rumpl** [comment]
Thanks! 

I wonder why git bash is doing that...
