### ISSUE TITLE
Allow scoped packages for special ESLint

### ISSUE THREAD

**Issue by goloroden** [depcheck/depcheck#174]
In the special handler for ESLint there is currently an option disabled where it is about scoped packages (see [this line of code](https://github.com/depcheck/depcheck/blob/fc44c61dfcc4e3e64c86bb87ce9e29a7dec8529e/src/special/eslint.js#L47)).

I would like to do something about it, but I am note sure what to do.

Basically, you could just say, that any scoped package is fine here. This would be the easiest change. Do you have any special ideas for this?

Please let me know and I can prepare a PR.

**Comment by lijunle** [comment]
Hi, @goloroden 

Basically, the idea is to look at the linked mentioned in the comment 3 lines above your referenced code. I think ESLint has a big change on that function now: https://github.com/eslint/eslint/blob/master/lib/config/config-file.js#L461

Read and understand how ESLint handles the scoped package case, then copy the pattern here.

I do a rough review on the newest ESLint code, it looks point to [this line](https://github.com/eslint/eslint/blob/master/lib/util/module-resolver.js#L71). BTW, I saw ESLint is support some `plugin:`, that looks new feature after my implementation.

Again, thank you for helping this. If you have any questions, please comment.

**Comment by goloroden** [comment]
Thanks for replying that fast :-)

I will have a look at this the day after tomorrow.
