### ISSUE TITLE
Recongnize the required module by nyc.

### ISSUE THREAD

**Issue by lijunle** [depcheck/depcheck#183]
[There](https://github.com/istanbuljs/nyc#support-for-custom-require-hooks-babel-webpack-etc) are three ways to require additional packages by nyc:

1. CLI: `nyc --require babel-register --require babel-polyfill mocha`
2. In `package.json`
3. In `.nycrc`

Should support the last two as MVP.

**Comment by rumpl** [comment]
not stale
