### ISSUE TITLE
add support for files with a node shebang

### ISSUE THREAD

**Issue by sevko** [depcheck/depcheck#19]
depcheck doesn't appear to take into account files without a `.js` extension but that contain a node shebang (eg `#!/usr/bin/env node`). Example:

```bash
$ tree -L 1
.
├── executable
├── node_modules
└── package.json

1 directory, 2 files

$ cat package.json
{
	"dependencies": {
		"through": "latest"
	}
}

$ cat executable
#!/usr/bin/env node
var through = require("through");

$ depcheck
Unused Dependencies
* through
```

Renaming `executable` to `executable.js` resolves the problem, though.

**Comment by sevko** [comment]
I can work on a PR for this later today.

**Comment by rumpl** [comment]
Hello, 

Yes, depcheck only checks [for js files](https://github.com/rumpl/depcheck/blob/master/index.js#L48). I'm not sure that `detective` can parse files with the shebang in them, if he can than that's great!

It would be great if there was a command line parameter for forcing additional files that are not `.js`.

Something like: `depcheck --additionnal=bin/main,bin/other`. What do you think about that ?

**Comment by sevko** [comment]
Since shebangs are only ever present at the beginning of a file, you can check the first line containing non-whitespace characters against a regular expression like `^[ \t]*#!.*node` (`jshint` somehow [implements this](https://github.com/jshint/jshint/issues/66)). A flag could be a useful additional feature.

**Comment by dominicbarnes** [comment]
+1

**Comment by lijunle** [comment]
The [**acorn**](https://www.npmjs.com/package/acorn) parse support `allowHashBang` options naturally.

**Comment by lijunle** [comment]
I think version 0.5.9 has supported this now. Could anybody help to test it?

I will add a test case to cover this later.
