### ISSUE TITLE
ignoreMatches does not work on  missing dependencies

### ISSUE THREAD

**Issue by goloroden** [depcheck/depcheck#190]
Supposed, I have a dependency in my `package.json` file that is not needed in my code, i.e. I have a unused dependency. Then, if I provide the dependency's name using `ignoreMatches`, anyway I won't get a warning. This is fine.

If I do the same thing with a missing dependency, i.e. I use it from within my code, but I don't add it to my `package.json` file, I *always* get a warning, no matter whether I provide the dependency's name using `ignoreMatches` or not.

Although this situation seems to be counter-intuitive (why would code run if dependencies are missing?), there are actually situations where this is meaningful.

Hence, could we update the `ignoreMatches` option to also be considered for missing dependencies?

**Comment by lijunle** [comment]
Awesome! This is @gregglind needs in #169.
