### ISSUE TITLE
Is it good to run at pre-commit level

### ISSUE THREAD

**Issue by awebdeveloper** [depcheck/depcheck#208]
Is it a good tool to run at pre-commit level. Check on each commit if something is missing/unused

**Comment by mnkhouri** [comment]
Hi @awebdeveloper, this tool might take too long (on a large codebase) for pre-commit -- though we'd like to improve that. I think it's a good tool for usage in CI. There are some improvements we can make for CI as well: https://github.com/depcheck/depcheck/issues/162

I'll be closing this issue, but please feel free to comment or open a new one with further issues!
