### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by nicolaerusan** [depcheck/depcheck#211]
I just hit this error while running depcheck on a project that has about 3200 NPM modules installed. Thought I'd share it for a heads up.

`<--- Last few GCs --->

  200749 ms: Mark-sweep 1387.6 (1435.2) -> 1387.6 (1435.2) MB, 1550.4 / 0.0 ms [allocation failure] [GC in old space requested].
  202167 ms: Mark-sweep 1387.6 (1435.2) -> 1387.5 (1419.2) MB, 1417.2 / 0.0 ms [last resort gc].
  203589 ms: Mark-sweep 1387.5 (1419.2) -> 1387.5 (1419.2) MB, 1422.0 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x17f6253cfb39 <JS Object>
    1: parseObj [/usr/local/lib/node_modules/depcheck/node_modules/babylon/lib/index.js:4020] [pc=0x14d1999b0106] (this=0x7f73ec3e619 <a Parser with map 0x3c8d0f3e9101>,isPattern=0x17f625304271 <false>,refShorthandDefaultPos=0x38749e922ee9 <an Object with map 0x3c8d0f3e7fd1>)
    2: parseExprAtom [/usr/local/lib/node_modules/depcheck/node_modules/babylon/lib/index.js:~3606] [pc=0x14d199926cf4] ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewTransitionArray(int) [/usr/local/bin/node]
 5: v8::internal::TransitionArray::Insert(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Map>, v8::internal::SimpleTransitionFlag) [/usr/local/bin/node]
 6: v8::internal::Map::CopyReplaceDescriptors(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::DescriptorArray>, v8::internal::Handle<v8::internal::LayoutDescriptor>, v8::internal::TransitionFlag, v8::internal::MaybeHandle<v8::internal::Name>, char const*, v8::internal::SimpleTransitionFlag) [/usr/local/bin/node]
 7: v8::internal::Map::CopyAddDescriptor(v8::internal::Handle<v8::internal::Map>, v8::internal::Descriptor*, v8::internal::TransitionFlag) [/usr/local/bin/node]
 8: v8::internal::Map::CopyWithField(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::FieldType>, v8::internal::PropertyAttributes, v8::internal::Representation, v8::internal::TransitionFlag) [/usr/local/bin/node]
 9: v8::internal::Map::TransitionToDataProperty(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::StoreFromKeyed) [/usr/local/bin/node]
10: v8::internal::LookupIterator::PrepareTransitionToDataProperty(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::StoreFromKeyed) [/usr/local/bin/node]
11: v8::internal::StoreIC::LookupForWrite(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [/usr/local/bin/node]
12: v8::internal::StoreIC::UpdateCaches(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [/usr/local/bin/node]
13: v8::internal::StoreIC::Store(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [/usr/local/bin/node]
14: v8::internal::Runtime_StoreIC_Miss(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
15: 0x14d1992092a7
16: 0x14d1999b0106
[1]    79166 abort      depcheck`

**Comment by jacalata** [comment]
I'm getting the same error, but I only have about 600 modules.

**Comment by InstanceOfMichael** [comment]
probably the same:
```
michael@michael-desktop:~/wa-1$ yarn security:depcheck
yarn run v1.7.0
$ depcheck

<--- Last few GCs --->

[12783:0x355d6c0]    38647 ms: Mark-sweep 1417.9 (1484.7) -> 1417.7 (1484.7) MB, 1049.9 / 3.5 ms  allocation failure GC in old space requested
[12783:0x355d6c0]    39418 ms: Mark-sweep 1417.7 (1484.7) -> 1417.7 (1453.7) MB, 770.6 / 6.0 ms  last resort GC in old space requested
[12783:0x355d6c0]    40294 ms: Mark-sweep 1417.7 (1453.7) -> 1417.7 (1453.7) MB, 876.7 / 5.9 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xaa136325879 <JSObject>
    1: stringSlice(aka stringSlice) [buffer.js:560] [bytecode=0x297aeb263fb1 offset=94](this=0x20e66ef822d1 <undefined>,buf=0xc51c1fa17f9 <Uint8Array map = 0x2ea291435a1>,encoding=0xaa136334ba1 <String[4]: utf8>,start=0,end=23460830)
    2: toString [buffer.js:633] [bytecode=0x297aeb263c01 offset=145](this=0xc51c1fa17f9 <Uint8Array map = 0x2ea291435a1>,encoding=0xaa136334ba1 <String[4]: utf8>,sta...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x8c20ec [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const>, v8::internal::PretenureFlag) [node]
 7: v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [node]
 8: node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding, v8::Local<v8::Value>*) [node]
 9: 0x8e2aa6 [node]
10: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
11: 0xad6f2c [node]
12: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
13: 0x2e9b0042fd
Aborted (core dumped)
```
also tried with `--max_old_space_size=4096`, but I ran out of system memory via OOM.
```
michael@michael-desktop:~/wa-1$ export NODE_OPTIONS=--max_old_space_size=4096
michael@michael-desktop:~/wa-1$ yarn security:depcheck
yarn run v1.7.0
$ depcheck
Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by daveisfera** [comment]
I was running into this as well and running `node --max-old-space-size=4096 <path_to>/depcheck` worked.

**Comment by heatherbooker** [comment]
Is there a way to run it and tell it only to check a max number of modules, so we can run it a couple times manually and get the benefits? ><

**Comment by csdfgraham** [comment]
export NODE_OPTIONS=--max_old_space_size=4096 didn't work, just get "killed" nothing in the logs whatsoever on fedora 30

**Comment by mindaugasnakrosis** [comment]
@nicolaerusan @daveisfera @csdfgraham did you manage to launch it someway? I am having the same problem.

**Comment by DanielPower** [comment]
I had this issue on Node 10, but switching to Node 12 fixed it.
