### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by sudo-suhas** [depcheck/depcheck#215]
The following dependencies are outdated:

|Package                |Current |Latest |Package Type   |
|-----------------------|--------|-------|---------------|
|babel-plugin-istanbul  |3.1.2   |4.1.4  |devDependencies|
|cross-env              |3.2.4   |5.0.1  |devDependencies|
|eslint                 |3.19.0  |4.2.0  |devDependencies|
|eslint-config-airbnb   |13.0.0  |15.0.2 |devDependencies|
|eslint-plugin-jsx-a11y |2.2.3   |6.0.2  |devDependencies|
|eslint-plugin-react    |6.10.3  |7.1.0  |devDependencies|
|fs-promise             |1.0.0   |2.0.3  |devDependencies|
|node-sass              |3.13.1  |4.5.3  |devDependencies|
|nyc                    |10.3.2  |11.0.3 |devDependencies|
|typescript             |1.8.10  |2.4.1  |devDependencies|
|yargs                  |6.6.0   |8.0.2  |dependencies   |

Additionally, the `fs-promise` module is now deprecated and use of either [`mz/fs`](https://github.com/normalize/mz) or [`fs-extra^3.0`](https://www.npmjs.org/package/fs-extra) is recommended.

I'd be more than happy to fix this in a PR but wanted to ask a question first.
Should node `v0.12` still be supported? Node `v0.12.x` [reached end-of-life](https://github.com/nodejs/LTS#lts-schedule) on 2016-12-31. Moreover, the latest [`yargs`](https://github.com/yargs/yargs/blob/master/CHANGELOG.md#800-2017-05-01) requires node 4+.

**Comment by lijunle** [comment]
No. Node v0.12 is not supported. I remember it is mentioned in README.

2017年7月18日 下午12:19，"Suhas Karanth" <notifications@github.com>写道：

**Comment by sudo-suhas** [comment]
From readme:
> Notice: depcheck needs node.js >= 0.12.

And in `package.json` the engines field also matches this - [`package.json#L7`](https://github.com/depcheck/depcheck/blob/master/package.json#L7)
