### ISSUE TITLE
error ELIFECYCLE

### ISSUE THREAD

**Issue by wesleymostien** [depcheck/depcheck#221]
What's the problem ? I got :

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hello@1.0.0 check: `npm-check --specials bin,webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hello@1.0.0 check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by wesleymostien** [comment]
more details:

11 silly lifecycle shizzlz@1.0.0~check: Returned: code: 1  signal: null
12 info lifecycle shizzlz@1.0.0~check: Failed to exec check script
13 verbose stack Error: shizzlz@1.0.0 check: `npm-check --specials bin,webpack`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/wmostien/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/wmostien/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by mnkhouri** [comment]
Hi @wesleymostien, it looks like you're using [`npm-check` (repo here)](https://github.com/dylang/npm-check). I'm not seeing anything in your output that points to an error with `depcheck` (this repo), so I'll close this issue, but please feel free to open another bug report if you note an issue in depcheck
