### ISSUE TITLE
Consider dependencies used when used in scripts

### ISSUE THREAD

**Issue by Ionaru** [depcheck/depcheck#222]
In my `package.json` I use ts-node to quickly run my program while developing, but depcheck says ts-node isn't used at all.

```json
  "scripts": {
    "start": "node --require ts-node/register src/index.ts"
  },
```

```
> depcheck
Unused devDependencies
* ts-node

```

Since I am using ts-node in an npm script, it shouldn't be caught by depcheck as an unused dependency.

**Comment by lijunle** [comment]
Hmm...

This is interesting. You are using `--require` parameter to declare dependency. The strings (`ts-node/register`) is not a `bin`, it is actually a module.
