### ISSUE TITLE
Add support for rollup configs

### ISSUE THREAD

**Issue by EdwardSalter** [depcheck/depcheck#231]
Rollup is a tool that is very similar to webpack and makes rather heavy usage of plugins.
At current, every single rollup dependency is showing as unused.

**Comment by mnkhouri** [comment]
I think this would be great to add! The [rollup config format](https://rollupjs.org/guide/en#using-config-files) looks straightforward to parse as a ["special"](https://github.com/depcheck/depcheck#special), for example like [babel](https://github.com/depcheck/depcheck/blob/master/src/special/babel.js)

**Comment by rumpl** [comment]
not stale
