### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by mattfysh** [depcheck/depcheck#247]
Hi @lijunle - I've noticed you've been merging pull requests to master... but have not been publishing updates to NPM. The last released version according to https://libraries.io/npm/depcheck was v0.6.8 on Oct 10, 2017

There have been a few merged pull requests since then, but these updates are not available if installing depcheck using your install instructions i.e. `npm install -g depcheck`

Any chance you could publish the latest code to npm? Looking for:

1. webpack2 support from #226 
2. restoration of `--specials` flag, which doesn't appear to be working in v0.6.8

thx

**Comment by lijunle** [comment]
So, I am sorry. I will publish it soon.

**Comment by lijunle** [comment]
@mattfysh I just push the tag 0.6.9. Once the [CI build](https://travis-ci.org/depcheck/depcheck) is finished, the new version should be published to NPM. 

Sorry that I miss your request!

**Comment by lijunle** [comment]
Done!

**Comment by mattfysh** [comment]
Awesome :D thank you @lijunle
