### ISSUE TITLE
Inline script commands in package.json are ignored

### ISSUE THREAD

**Issue by dunnkers** [depcheck/depcheck#257]
When a dependency is only used inside parenthesis of another command in `package.json` scripts, depcheck marks this dependency as unused. e.g.:

```json
  "scripts": {
    "start": "concurrently \"cross-env BROWSER=none yarn browser\" \"wait-on http://localhost:3000 && electron .\""
  },
  "devDependencies": {
    "concurrently": "^3.5.1",
    "cross-env": "^5.1.6",
    "wait-on": "^2.1.0"
  }
```

Here, `cross-env` and `wait-on` are marked as **unused**.

Besides, thanks for the useful plugin! Great work. 🥂

**Comment by jakeleventhal** [comment]
I have this same problem with `husky` and `jest-junit`

**Comment by lijunle** [comment]
@dunnkers IIRR, depcheck [use space](https://github.com/depcheck/depcheck/blob/master/src/special/bin.js#L49) to split the content for recognizing the executable. Could you please try to write the following command and check if your issue is mitigated?

```
concurrently \" cross-env BROWSER=none yarn browser \" \" wait-on http://localhost:3000 && electron .\"
```

@jakeleventhal How does your command look like? Does your issue get mitigated after insert some spaces?

**Comment by jakeleventhal** [comment]
For jest-junit I have it as a parameter, so i dont think spacing will work:
`"scripts": {
    "test-cov": "JEST_JUNIT_OUTPUT='./test-reports/test-report.xml' jest --coverage --reporters=default --reporters=jest-junit --detectOpenHandles --forceExit --silent"
  }`

For husky, it is its own section in my package.json:
`"husky": {
    "hooks": {
      "pre-push": "npm run lint"
    }
  },
  "devDependencies": {
...
`

**Comment by jakeleventhal** [comment]
any updates on this?

**Comment by rumpl** [comment]
Not yet, @jakeleventhal would you like to make a PR for this one?

**Comment by jakeleventhal** [comment]
I would like to but I am very busy. I don't mind waiting.

**Comment by jakeleventhal** [comment]
This is still an issue!

**Comment by rumpl** [comment]
👍

**Comment by jakeleventhal** [comment]
this is still an issue!!

**Comment by jakeleventhal** [comment]
@rumpl I am not sure if this is related, but i know `nom-check` uses this library. This issue may be due to the same underlying issue
https://github.com/dylang/npm-check/issues/136

**Comment by rumpl** [comment]
@jakeleventhal thanks for pinging me, will take a look.

**Comment by jakeleventhal** [comment]
@rumpl any update here?

**Comment by jakeleventhal** [comment]
This is not stale! can we reopen this

**Comment by jakeleventhal** [comment]
reopened here https://github.com/depcheck/depcheck/issues/584
