### ISSUE TITLE
support for multiple entry points

### ISSUE THREAD

**Issue by jonathanong** [depcheck/depcheck#26]
seems like it detects all my client-side dependences as unused as they have a different entry point which isn't defined in main. also, our grunt dependencies are not included either. can we have an option to manually input multiple entry points?

**Comment by jonathanong** [comment]
actually... this might be because all my client-side code is ES6+. not sure

**Comment by lijunle** [comment]
Seem a dup of #21

**Comment by lijunle** [comment]
Closing this issue because no follow ups. If get any concerns, please reply.
