### ISSUE TITLE
Add pre-commit to specials

### ISSUE THREAD

**Issue by bennypowers** [depcheck/depcheck#261]
`pre-commit` is a handy npm package that lets maintainers run their package scripts in pre-commit hooks. It's use looks like this:

```json
{
  "pre-commit": [
    "lint"
  ],
  "devDependencies": {
    "pre-commit": "^1.2.2"
  }
}
```

It should be added to the list of default specials

**Comment by rumpl** [comment]
Thanks for the report @bennypowers, would you like to make a PR for this one?

**Comment by rumpl** [comment]
not stale
