### ISSUE TITLE
False "unused dependencies" for `export ... from ...`

### ISSUE THREAD

**Issue by kaime** [depcheck/depcheck#262]
I'm using a lot lines like this one:

```js
export { Foo as Bar} from 'some-package'
```
If a package is used only this way, depcheck will issue an "unused dependency" message. If I change it to this other equivalent code, then it won't detect as unused.

```js
import { Foo as Bar } from 'some-package'
export { Bar }
```

**Comment by mnkhouri** [comment]
Thanks for the report @kaime! I've added some tests to reproduce this bug in #272
