### ISSUE TITLE
Deploy failed (invalid NPM token?)

### ISSUE THREAD

**Issue by mnkhouri** [depcheck/depcheck#275]
The deploy for version 0.6.10-beta.0 failed, see log [here](https://travis-ci.org/depcheck/depcheck/jobs/415614637#L2784). NPM [revoked all tokens 1 months ago](https://status.npmjs.org/incidents/dn7c1fgrr7ng), so I think our token needs to be updated

-----------------

For new token: https://www.npmjs.com/settings/lijunle/tokens

To [update travis](https://docs.travis-ci.com/user/encryption-keys/#usage): `travis encrypt api_key ="TOKEN VALUE" --add`

**Comment by mnkhouri** [comment]
@lijunle might you have a chance to update this token this weekend? We can then get 0.6.10 released :)

**Comment by lijunle** [comment]
@mnkhouri I just added you to the npm package maintainer list.

I don't find @LinusU user name in npm. What is your name?

**Comment by mnkhouri** [comment]
Thanks @lijunle !

**Comment by mnkhouri** [comment]
@LinusU I noticed your npm username is `linusu` -- I have invited you to the maintainer list as well
