### ISSUE TITLE
Add support for Jest

### ISSUE THREAD

**Issue by hassankhan** [depcheck/depcheck#285]
### Feature request description
It would be awesome if `depcheck` could exclude Jest as well as any transformer modules [as per the documentation](https://jestjs.io/docs/en/configuration.html#transform-object-string-string).

### Code snippets (if applicable)
How the dependency is used (if applicable):

```json
// jest.config.js
"transform": {
  ".(ts|tsx)": "ts-jest"
},
```

How the dependency is listed in package.json (if applicable):

```
package.json snippet here
please include the section name (e.g. devDependencies, dependencies)
{
  "devDependencies": {
    "jest": "^23.0.0"
  }
}
```

**Comment by mnkhouri** [comment]
Hi @hassankhan, thank you for the detailed suggestion! Based on the documentation you linked, the detection seems fairly straightforward, so I think it should relatively easy to add this support as a ["special"](https://github.com/depcheck/depcheck#special), for example like [babel](https://github.com/depcheck/depcheck/blob/master/src/special/babel.js). 

If you have the time to try out a PR for this, it would be greatly appreciated! No problem if not, of course -- hopefully we can get to it soon
