### ISSUE TITLE
False alert for ejs package using expressjs

### ISSUE THREAD

**Issue by AndreaFranchini** [depcheck/depcheck#289]
Building an Express.js application specifying

```app.set('view engine', 'ejs');```

involves to install the ejs package.
Depcheck shows:

```
$ depcheck
Unused dependencies
* ejs
```

that is a false alert.
Maybe is possibile to configure depcheck to consider the express framework peculiarities.

**Comment by LinusU** [comment]
Yes, I really which we hadn't taken this approach in express, should probably bring that up so that we can change it in v5...

That being said, a workaround for now could be to do:

```diff
 const express = require('express')
+const ejs = require('ejs')

 const app = express()

-app.set('view engine', 'ejs')
+app.set('view engine', ejs.name)
