### ISSUE TITLE
depcheck error for workbox-build

### ISSUE THREAD

**Issue by peterennis** [depcheck/depcheck#290]
This result is false:

```
C:\ae\adaept.com>depcheck ae-svg-components
Unused devDependencies
* workbox-build

C:\ae\adaept.com>
```

This repo/commit: https://github.com/peterennis/ae-svg-components/commit/279e536bf3f89dc45f7a013af4bcbaffa1c77f69

`workbox-build` is required for `npm run build --prod` and the Stencil
build process will notify if it is missing.

**Comment by LinusU** [comment]
Hmmm, shouldn't the Stencil package have a dependency on `workbox-build`? 🤔

**Comment by peterennis** [comment]
Updated to latest Stencil

```
C:\ae\adaept.com\_components_>depcheck ae-svg-components
Unused devDependencies
* workbox-build
```

From here:
https://github.com/ionic-team/stencil/blob/master/package.json

```
  "lazyDependencies": {
    "@types/jest": "~23.3.1",
    "@types/puppeteer": "^1.6.4",
    "jest": "~23.6.0",
    "jest-cli": "~23.6.0",
    "pixelmatch": "4.0.2",
    "puppeteer": "~1.8.0",
    "workbox-build": "~3.4.1"
  },
```

When I use the "lazyDependencies"  and fix the "devDependencies" I get:

```
C:\ae\adaept.com\_components_>depcheck ae-svg-components
No depcheck issue
```

So that looks like the solution.
