### ISSUE TITLE
doesn't seem to detect require('os') in source

### ISSUE THREAD

**Issue by marcjordan** [depcheck/depcheck#294]
### Bug Description
In my code, I have:

```
const os = require('os');
```

Yet depcheck seems to think the os module is unused. Also, if I have not installed the 'os' module in package.json, I don't get the missing package warning

### Code snippets
Where the dependency is used:

```
/* eslint-disable no-unused-vars */

const optimist = require('good');
const os = require('os');
```

Where the dependency is listed in package.json:

```
{
  "dependencies": {
    "good": "0.0.1",
    "os": "^0.1.1"
  }
}
```

### Versions
 - `node -v`: 6.14.3
 - `npm -v`: 6.4.1
 - `depcheck -v`: 0.6.11

### Extra info
The example above was just using the good package from the depcheck/depcheck-test-e2e repo on GitHub.

**Comment by rumpl** [comment]
Hi @marcjordan,

The `os` package is a nodejs core module and shouldn't be installed, [see here](https://github.com/DiegoRBaquero/node-os).

Depcheck filters all the builtin modules that you `require` or `import` in your code and hence it will tell you that the package is unused, meaning you don't really need to install it (see the source code of `node-os`, it just exports the core `os` module).
