### ISSUE TITLE
Using own package name in import statement causes missing dependency error

### ISSUE THREAD

**Issue by korob93** [depcheck/depcheck#297]
### Bug Description
Let's assume I have a package `my-awesome-package` with the following structure:
```
|-package.json
|+foo
  |+bar
    |-index.js
|-constants.js
```
So, in my index.js I'd like to use some constants, but for some reason instead of doing
```
import { PI } from "../../constants";
```
I prefer to use
```
import { PI } from "my-awesome-package/constants";
```
So when I run depcheck it throws a missing dependency error

### Versions
 - `node -v`: v8.11.4
 - `npm -v`: 5.6.0
 - `depcheck -v`: 0.6.1

### Extra info
I'm not quite sure about how cool using import statements containing own package name is, but it looks ok for me

**Comment by LinusU** [comment]
Not saying that we shouldn't support it, but Node.js doesn't support that pattern and will complain that it `Cannot find module 'my-awesome-package/constants'`...

**Comment by korob93** [comment]
Hello @LinusU! Thank you for quick reply.

I agree with you, but in case `my-awesome-package` is not intended to be used independently (a react component library for example or some stuff like that) everything will be resolved without any problems.

For example I have my package.json like this
```
{
  "name": "my-main-application",
  "dependencies": {
    "my-awesome-package": "*"
  }
  ...
}
```
And then somewhere in my application code i have the following import statement
```
import "my-awesome-package/foo/bar";
```
In that case everything works fine

**Comment by LinusU** [comment]
depcheck should correctly support the way you're describing in your last post, is there a problem with this for you?

**Comment by LinusU** [comment]
Sorry if for asking so many questions, but is there a file under `node_modules/my-awesome-package` that is using `require('my-awesome-package/...')`?

e.g.

```text
~/my-main-application/index.js
  require('my-awesome-package')

~/my-main-application/node_modules/my-awesome-package/index.js
  require('my-awesome-package/other-file')

~/my-main-application/node_modules/my-awesome-package/other-file.js
  module.exports = /* ... */
```

**Comment by korob93** [comment]
@LinusU sorry for confusing you, `npx depcheck node_modules/my-awesome-package` works ok.

Maybe it will be more convinient for you to chek out my [example repo](https://github.com/korob93/depcheck-examlpe)?

**Comment by matz3** [comment]
I fully agree with @phil-lgr. This should not cause a missing dependency issue in case the package defines "exports" in the `package.json`.
