### ISSUE TITLE
Check child_processes

### ISSUE THREAD

**Issue by stevenvachon** [depcheck/depcheck#302]
### Feature request description
It's possible for a child process to execute an npm package's binary. Such should be checked as thoroughly as possible.

**Comment by rumpl** [comment]
Hey,

Could you elaborate please? Not sure I understand.

**Comment by stevenvachon** [comment]
```js
require('child_process').spawn('./node_modules/mypackage/bin/mybin');
```
```js
require('child_process').spawn('npx mybin');
```

**Comment by rumpl** [comment]
I'm not sure I want depcheck to go this deep into reading the code, reading imports from the code and the configuration files of different tools is complicated enough as it is.
