### ISSUE TITLE
babel-polyfill imported by useBuiltIns

### ISSUE THREAD

**Issue by stevenvachon** [depcheck/depcheck#303]
### Bug Description
With `useBuiltIns: 'usage'` in a Babel config, parts of the babel-polyfill package will be [imported automatically](https://github.com/babel/website/issues/1660#issuecomment-390311626). Because depcheck does not recognize this, it notifies false negatives.

### Versions
 - `node -v`: 10.11.0
 - `npm -v`: 6.4.1
 - `depcheck -v`: 0.6.11

**Comment by rumpl** [comment]
Thanks for reporting this, are you willing to make a PR for this one?

**Comment by stevenvachon** [comment]
@rumpl Not at this time. I'm not currently using this anywhere.
