### ISSUE TITLE
Be more explicit about core NodeJs modules

### ISSUE THREAD

**Issue by rumpl** [depcheck/depcheck#308]
### Explicitly list used core NodeJs modules as not needed

Instead of listing core NodeJs dependencies as unused maybe we could say that they are not needed, people are (rightfully) getting confused.

### Code snippets
How the dependency is used :

```
var qs = require('querystring');
```

How the dependency is listed in package.json:

```
{
  "name": "tests-deps",
  "description": "qsdf",
  "version": "1.0.0",
  "licence": {
    "license": "qsdf"
  },
  "dependencies": {
    "querystring": "^0.2.0"
  }
}
```

This setup prints out
```
Unused dependencies
* querystring
```

Which confuses people, we should separate the used core modules and explicitly say that it's not needed, something like: 
```
Not needed dependencies
* querystring
```

**Comment by rumpl** [comment]
not stale haha

**Comment by rumpl** [comment]
Go away bot

**Comment by mpacary** [comment]
[This technique to retrieve dynamically the list of NodeJS core modules](https://stackoverflow.com/a/35825896/488666) could be useful..
