### ISSUE TITLE
includeDirs

### ISSUE THREAD

**Issue by dkebler** [depcheck/depcheck#31]
Enhancement:

To compliment your ignoreDirs how about includeDirs?  Default is all directories below the cwd or a given path if not used.  Otherwise just the array of given includeDirs.   

In a project typically I would have only one or two directories I want checked.  Using ignoreDirs I must specify a longer list of directories that changes and is thus harder to maintain.

Seems like maybe you aren't doing much with this repo at this time.  I might eventually get around to a PR for this.

**Comment by lijunle** [comment]
Please update to [0.5.9 release](https://www.npmjs.com/package/depcheck) to get this feature.

Use as `--ignore-dirs=a,b,c`.
