### ISSUE TITLE
False positiv husky

### ISSUE THREAD

**Issue by VincentLanglet** [depcheck/depcheck#315]
### Bug Description
Unused devDependencies

### Code snippets
Used in the package json.
```
"husky": {
    "hooks": {
      "pre-commit": "yarn tsc && yarn lint-staged"
    }
  },
```

### Versions
 - `node -v`: 11.6.0
 - `npm -v`: 6.5.0-next.0
 - `depcheck --version`: 0.7.1

**Comment by VincentLanglet** [comment]
This still should be fixed

**Comment by rumpl** [comment]
Fixed, merged, will be available in the next release

Thank you for your patience.

**Comment by rumpl** [comment]
@VincentLanglet if you want, you can make the PR to DefinitelyTyped once I release this

**Comment by VincentLanglet** [comment]
@rumpl I can, (and will do the same for lint-staged).

What about including the types in this project ?
The file https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/depcheck/index.d.ts is not big, the update would be easier.

**Comment by rumpl** [comment]
Yeah sure, we can include it, I have no idea how that works, we just publish depcheck with this .d.ts file and we are good to go?

**Comment by VincentLanglet** [comment]
@rumpl I think this (https://github.com/depcheck/depcheck/pull/458) is enough
