### ISSUE TITLE
False positive stryker reporter/parser

### ISSUE THREAD

**Issue by VincentLanglet** [depcheck/depcheck#317]
### Bug Description
Missing
```
* stryker-html-reporter
* stryker-jest-runner
* stryker-typescript
```

### Code snippets
stryker.conf.js
```
module.exports = function(config) {
  config.set({
    mutate: [
      'src/**/*.ts?(x)',
      '!src/**/index.ts?(x)',
      '!src/setupTests.ts',
      '!src/services/testUtils.ts',
      '!src/**/*.test.ts?(x)',
    ],
    mutator: 'typescript',
    testRunner: 'jest',
    reporters: ['progress', 'clear-text', 'html'],
    coverageAnalysis: 'off',
    jest: {
      projectType: 'react',
    },
  });
};

```

Where the dependency is listed in package.json:

```
    "stryker": "^0.34.0",
    "stryker-api": "^0.23.0",
    "stryker-html-reporter": "^0.17.0",
    "stryker-jest-runner": "^1.3.0",
    "stryker-typescript": "^0.17.0",
```

### Versions
 - `node -v`: 11.6.0
 - `npm -v`: 6.5.0-next.0
 - `depcheck --version`: 0.7.1

**Comment by rumpl** [comment]
Thanks for reporting this!

I had no idea things like stryker existed, it looks awesome! :)

**Comment by VincentLanglet** [comment]
FYI, now the dependencies are named
```
"@stryker-mutator/core": "^1.0.2",
"@stryker-mutator/html-reporter": "^1.0.2",
"@stryker-mutator/jest-runner": "^1.0.2",
"@stryker-mutator/typescript": "^1.0.2",
...
```

**Comment by VincentLanglet** [comment]
This still should be fixed

**Comment by rumpl** [comment]
Hey @VincentLanglet from your example I don't see where the 3 dependencies are used in your code, could you update it?

**Comment by VincentLanglet** [comment]
This is a monorepository now, so the librairies are
```
* @stryker-mutator/html-reporter
* @stryker-mutator/jest-runner
* @stryker-mutator/typescript
...
```

In the config
```
module.exports = function(config) {
  config.set({
    mutate: [
      'src/**/*.ts?(x)',
      '!src/**/index.ts?(x)',
      '!src/setupTests.ts',
      '!src/services/testUtils.ts',
      '!src/**/*.test.ts?(x)',
    ],
    mutator: 'typescript',
    testRunner: 'jest',
    reporters: ['progress', 'clear-text', 'html'],
    coverageAnalysis: 'off',
    jest: {
      projectType: 'react',
    },
  });
};
```

The key `mutator` is for the dependency `@stryker-mutator/typescript`, there is also a javascript or a vue mutator.
The value `html` for the key `reporters` is for the `@stryker-mutator/html-reporter`.
The key `testRunner` is for the dependency `@stryker-mutator/jest-runner`, there is also jasmine, karma, mocha, ...

There is the list of plugin here: https://stryker-mutator.io/stryker/plugins

**Comment by VincentLanglet** [comment]
Not stale

**Comment by VincentLanglet** [comment]
Still not stale, @rumpl Is there a way to avoid the closing of the issue ?
They are still not solved.
