### ISSUE TITLE
export { x } from '@Y';  - @Y is not recognized as a required dependency

### ISSUE THREAD

**Issue by mkaufma** [depcheck/depcheck#321]
### Bug Description
A description of the bug

### Code snippets
Where the dependency is used:
```
export { default as request } from 'request';
export { passphraseEncrypt } from "@stellar-fox/cryptops";
```

Where the dependency is listed in package.json:

```
"@stellar-fox/cryptops": "^1.0.4",
"request": "^2.88.0"
```

### Versions
 - `node -v`: v10.14.0
 - `yarn -v`: 1.13.0
 - `depcheck --version`: ^0.6.9

**Comment by rumpl** [comment]
Thanks for reporting this.

Wow, this is a tricky one...
