### ISSUE TITLE
Depcheck is not counting dependencies in JSX files and detects itself

### ISSUE THREAD

**Issue by seantcanavan** [depcheck/depcheck#340]
### Bug Description
Depcheck detects itself and reports itself as not being used which is slightly amusing. 

It also appears not to be counting instances of imports being used in JSX files.

```
Fri Apr 19 09:55 AM master-chief: node ./node_modules/depcheck/bin/depcheck.js .
Unused devDependencies
...
* depcheck
...
* react-dropzone
...
* webpack-cli
```

### Code snippets
Where the dependency is used:

index.jsx:
```
import Dropzone from 'react-dropzone';
...
        <Dropzone
          accept={accept}
          activeClassName={style.active}
          acceptClassName={style.accepted}
          rejectClassName={style.rejected}
          onDropAccepted={this.onDropAccepted}
          onDropRejected={this.onDropRejected}
          className={style.dropzone}
          multiple={multiple}
          maxSize={maxSize}
        >
```

Where the dependency is listed in package.json:
devDependencies
```
    "react-dropzone": "4.2.8",
```

### Versions
 - `node -v`: 8.15.1
 - `npm -v`: 6.4.1
 - `depcheck --version`: 0.7.2

### Extra info
I can't include the JSON output because it contains privileged information unfortunately. Sorry!

**Comment by rumpl** [comment]
Hey,

Could gou give us the output of depcheck —json please?

**Comment by seantcanavan** [comment]
I can't share the JSON unfortunately due to the sensitive nature of the output. I've since run it again however and it's no longer detecting itself but still not finding references in JSX files it would seem. `Dropzone` is used in exactly one file and it's a `.jsx` file so that's why I'm assuming it's missing JSX files. 

Is there a parameter I'm missing? I thought JSX files were supported.

**Comment by KaboomFox** [comment]
Did you try adding ```specials: [
        depcheck.special.webpack
]```?

**Comment by seantcanavan** [comment]
Where exactly would this argument be added to @KaboomFox ?

**Comment by KaboomFox** [comment]
Try something like this ```const options = {
  parsers: { // the target parsers
    '*.js': depcheck.parser.es6,
    '*.jsx': depcheck.parser.jsx
  },
  specials: [ // the target special parsers
    depcheck.special.eslint,
    depcheck.special.webpack
  ],
};

depcheck('/path/to/your/project', options, (unused) => {
  console.log(unused.dependencies); // an array containing the unused dependencies
  console.log(unused.devDependencies); // an array containing the unused devDependencies
  console.log(unused.missing); // a lookup containing the dependencies missing in `package.json` and where they are used
  console.log(unused.using); // a lookup indicating each dependency is used by which files
  console.log(unused.invalidFiles); // files that cannot access or parse
  console.log(unused.invalidDirs); // directories that cannot access
});```

**Comment by seantcanavan** [comment]
Sorry I know it's been a long time. Thanks so much to @KaboomFox for getting me this far.

I tried running it with `npm install -g depcheck` and creating `depcheck.js` with her code snippet but got an error saying `depcheck` was missing so I just added it to the `package.json` file and did `const depcheck = require("depcheck")` at the top of the `depcheck.js` file I made.

I had to add a couple internal-only folders to the ignoreDirs array which worked great but I'm having issues with flow type imports now.

1. `'/work/team/project/src/app/actions.js': { SyntaxError: Unexpected token (22:12)`

Caused by: `import type { Action } from '../_shared/actions/actions';`


2. `'/work/team/project/src/app/components/app.jsx': { SyntaxError: Unexpected token (2:12)`

Caused by: `import type { ElementRef } from 'react';`

I checked the parser page on GitHub and didn't see any direct mention of a `flow` parser to support the `type` syntax.

I apologize I'm still decently new to JavaScript but other than these errors I did get output from the files that were successfully parsed. Any ideas on how to get past these new errors?

**Comment by rumpl** [comment]
@seantcanavan please don’t apologize, we are here to help and try to make depcheck work for you :)
It’s the evening in Europe, I’ll take a closer look tomorrow.

**Comment by rumpl** [comment]
not stale

**Comment by patcon** [comment]
> it's no longer detecting itself

for the next person who comes along, probably because you added `depcheck` into a `scripts` command of your package.json file, and have the `bin` special enabled now :)

(took me awhile to sort that out as well..)
