### ISSUE TITLE
peerDepdencies of a used package not considered

### ISSUE THREAD

**Issue by daveisfera** [depcheck/depcheck#341]
### Bug Description
A package that's only in `peerDependencies` of a used package is still marked as unused even though it really is used.

### Code snippets
Where the dependency is used:

```
const jsdomGlobal = require('jsdom-global');
```

Where the dependency is listed in package.json:

```
{
  "name": "test_depcheck",
  "license": "PUBLIC DOMAIN",
  "dependencies": {
    "jsdom": "~11.11.0",
    "jsdom-global": "~3.0.2"
  }
}
```

### Versions
 - `node -v`: v10.15.2
 - `npm -v`: 6.4.1
 - `depcheck --version`: 0.7.2

### Extra info
If you remove `jsdom` from `package.json`, then `yarn install` gives the following error and the code doesn't work:
```
yarn install v1.13.0
warning package.json: License should be a valid SPDX license expression
warning test_depcheck: License should be a valid SPDX license expression
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > jsdom-global@3.0.2" has unmet peer dependency "jsdom@>=10.0.0".
[4/4] 🔨  Building fresh packages...

success Saved lockfile.
✨  Done in 0.70s.
```

json output:
```
{"dependencies":[],"devDependencies":[],"missing":{},"using":{"jsdom-global":["/Users/dlj/temp/index.js"],"jsdom":["/Users/dlj/temp/index.js"]},"invalidFiles":{},"invalidDirs":{}}
```

**Comment by rumpl** [comment]
Hey, I see that you created a test module, could you push it on github please?

You talk about `devDependencies` but in your package.json your deps are in `dependencies`, also I'm not sure which one is marked as unused, is it `jsdom` or `jsdom-global`?

**Comment by daveisfera** [comment]
There's not anything more to add then what I included in the bug and I just realized that I had a typo in the original submission. I meant to write `peerDependencies` and accidentally wrote `devDependencies`. Here's the link to the code that's "causing the problem":
https://github.com/rstacruz/jsdom-global/blob/371c36a2b64a7c2d014260212cc1a22a6bd1de2b/package.json#L24

**Comment by rumpl** [comment]
Understood, thanks for reporting this, we don’t look at peer dependencies, we should I gues

**Comment by rumpl** [comment]
I'm going to close this one since [we already support and have a test for peer dependencies](https://github.com/depcheck/depcheck/tree/master/test/fake_modules/peer_dep). 

If you still have problems please open a new issue with a reproducible repo.

Thanks

**Comment by dave-nm** [comment]
The file in the original comment reproduces the issue.

**Comment by rumpl** [comment]
@dave-nm I just made a test with `jsdom` and `jsdom-global` ([see here](https://github.com/depcheck/depcheck/pull/348)), could you take a look and tell me if this is what you have? The test passes, jsdom is found as a dependency. There must be something else that is blocking depcheck. I am going to need you to tell me more about your setup if you want me to help you.

Cheers.

**Comment by rumpl** [comment]
Keep in mind that, in order for peer dependencies to work, you need to do a `npm install` (or `yarn` or whatever).

If there are no `node_modules` where `depcheck` can read your depency `package.json` then depcheck can't read and check your peer dependencies.

**Comment by daveisfera** [comment]
You're right. The issue was that my `node_modules` wasn't up to date and so the necessary `peerDependencies` info wasn't there.

**Comment by rumpl** [comment]
Nice! 

Thanks for updating the issue ^^

**Comment by daveisfera** [comment]
I just realized what the actual problem is. We're using [yarn workspaces](https://yarnpkg.com/en/docs/workspaces), so the `package.json` of the peer dependency is in the `node_modules` in the parent directory and `depcheck` isn't loading that info and that's why it's warning about an unused dependency that really is used.

**Comment by robross0606** [comment]
This still appears to be happening.  My project has a peer dependency on `prom-client`:
```
npm WARN prometheus-gc-stats@0.5.1 requires a peer of prom-client@>= 10 < 12 but none is installed. You must install peer dependencies yourself.
```
However, `depcheck` lists it as unused after installation:
```
C:\Code\code>depcheck --version
1.4.0

C:\Code\code>depcheck
Unused dependencies
* prom-client
```

**Comment by rumpl** [comment]
@robross0606 could you open a new issue and provide a repository reproducing this error please?
