### ISSUE TITLE
Mocha registering as Unused even with --specials=mocha

### ISSUE THREAD

**Issue by jrgleason** [depcheck/depcheck#342]
### Bug Description
When I try to run `depcheck ./ --specials=mocha` in a project where tests are ran like `mocha --delay --exit ./test/suite.js` I still get...

```
Unused devDependencies
* chai
* mocha
* nyc
* rollup
* sinon

npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
```

### Versions
 - `node -v`: v10.12.0
 - `npm -v`: 6.4.1
 - `depcheck --version`: 0.6.11

### Extra info

The --json command didn't do anything.

**Comment by rumpl** [comment]
Hey, could you try with the lastest depcheck version please?

**Comment by jrgleason** [comment]
That is difficult because my company regulates the versions we can use. Is there another issue that may explain this behavior?

**Comment by rumpl** [comment]
Can you try and run `npx depcheck ....` ?

**Comment by jrgleason** [comment]
Sure what should I put in the ...

**Comment by jrgleason** [comment]
Also I have the following...

`import { MyObj } from "@me/project";

and I it is still showing up in the unused. BTW this is `--experimental-modules` using mjs files

**Comment by jrgleason** [comment]
`"install:depCheck": "npx depcheck --specials=mocha"`

same result

**Comment by jrgleason** [comment]
Also tried `--detectors=importDeclaration` but it didn't help. Are there special things you need for ES6?

**Comment by rumpl** [comment]
Not really no

**Comment by jrgleason** [comment]
I am using ESM not CommonJS FYI

**Comment by rumpl** [comment]
Shouldn't be a problem

**Comment by jrgleason** [comment]
Also tried this https://gist.github.com/jrgleason/07b867ba77d9766b87c6946a158bec56 then called with `"install:depCheck": "node --experimental-modules depcheck.mjs"` but still not working

**Comment by jrgleason** [comment]
I will try to put together a simple example so I can share ASAP

**Comment by jrgleason** [comment]
oops 

```
parsers: { // the target parsers
        '*.mjs': depcheck.parser.es6
    },
``` 

helped a bit :-)

**Comment by jrgleason** [comment]
But mocha is still not working

**Comment by jrgleason** [comment]
This is how mocha is configured to use MJS

https://gist.github.com/jrgleason/83c30e6651b83a3521cb767a834f763a

**Comment by jrgleason** [comment]
BTW for now 

```
ignoreMatches: [ // ignore dependencies that matches these globs
        'mocha',
        'nyc',
        'rollup'
    ]
```

**Comment by jrgleason** [comment]
Sorry still working on example. In the meantime webpack and babel appear to have issues too...

```
specials: [ // the target special parsers
        depcheck.special.eslint,
        depcheck.special.mocha,
        depcheck.special.webpack,
        depcheck.special.babel
    ]

```

```
Unused dev @babel/register,babel-loader,css-loader,html-loader,istanbul,style-loader,url-loader,webpack,webpack-cli 9
```
