### ISSUE TITLE
Invalid files caused by flow type annotations?

### ISSUE THREAD

**Issue by jrnail23** [depcheck/depcheck#353]
How do I get depcheck to properly handle files with flow type annotations in them?

**Comment by rumpl** [comment]
Thanks for reporting this @jrnail23, indeed depcheck doesn't know how to parse flow annotations, we could just add the plugin for babel and make it work, will try to do something for this soon.

**Comment by jrnail23** [comment]
@rumpl, FYI, I tried your suggestion by the existing jsx parser and adding `flow` and `flowComments`, and it seems to have worked for me.  I can create a PR for that if you like (I assume you'd want it in both the jsx and the es7 parsers, right?).

**Comment by rumpl** [comment]
Great! Sure go ahead, I would gladly merge this :)

Thanks!

**Comment by jrnail23** [comment]
@rumpl, the PR is up, ready for your review :-)

**Comment by rumpl** [comment]
Aaand merged! :)

Do you want me to publish a new release?

**Comment by jrnail23** [comment]
@rumpl, yes please!  sorry, I didn't see this reply before mentioning the new version in my PR comments.
:-D

**Comment by rumpl** [comment]
I just pushed the 0.8.3 tag, it will be up on npm as soon as the tests pass 

Cheers

**Comment by jrnail23** [comment]
Thanks!
