### ISSUE TITLE
False positive: React-select

### ISSUE THREAD

**Issue by s-Hale** [depcheck/depcheck#356]
### Bug Description
Detects react-select as unused: we actually use it rather extensively.

### Code snippets
Where the dependency is used:

```
import { components } from 'react-select';

import Select from 'react-select';
```

Where the dependency is listed in package.json:
```
    "react-select": "^2.3.0",
```
It's in dependencies.

**Comment by rumpl** [comment]
@s-Hale thanks for reporting this, I am going to need some more information for this please
