### ISSUE TITLE
False positive: autosuggest-highlight

### ISSUE THREAD

**Issue by s-Hale** [depcheck/depcheck#357]
### Bug Description
Detects as unused, it isn't.

### Code snippets
Where the dependency is used:

```
import autosuggestHighlightMatch from 'autosuggest-highlight/match';
```
Called a few lines later.

Where the dependency is listed in package.json:

```
    "autosuggest-highlight": "^3.1.1",
```
Dependencies.

**Comment by rumpl** [comment]
not stale
