### ISSUE TITLE
False positive when only importing typescript interfaces (so no runtime code) from a package

### ISSUE THREAD

**Issue by Zjaaspoer** [depcheck/depcheck#359]
### Bug Description
Only importing TypeScript interfaces (so no runtime code) provides false positives.

### Versions
 - `depcheck --version`: 0.8.1

### Extra info
It seems like the analysis is done on the compiled code and therefore won't know about the imported interfaces (as they are removed during compilation)?

**Comment by rumpl** [comment]
Hey, thanks for reporting this, yes this is a known issue, the fix is to use the typescript parser and not babel for typescript files, will get to it as soon as I have some time.

I'll close this one since we already have a ticket for this #163 

Cheers

**Comment by Zjaaspoer** [comment]
ah ok, thanks, will track that ticket!
