### ISSUE TITLE
False alert on vue-click-outside

### ISSUE THREAD

**Issue by tiagoppinho** [depcheck/depcheck#361]
There is a false alert of unused dependency when using [vue-click-outside](https://www.npmjs.com/package/vue-click-outside).

**Usage**
```js
import ClickOutside from 'vue-click-outside'

export default {
  name: 'Dropdown',
  directives: {
    ClickOutside
  },
  props: {
    ...
  },
  data () {
    return {
      ...
    }
  }
}
```

**Depcheck json output**
```json
{
  "dependencies": ["vue-click-outside"],
  "devDependencies": [
    ...
  ],
  "missing": {},
  "using": {
    ...
  },
  "invalidFiles": {
    ...
  },
  "invalidDirs": {}
}
```

**Comment by rumpl** [comment]
Thanks for reporting this, could you paster the *whole* output of depcheck json?

Even better, if this is an open source project could you give us the link? 

If not, would it be possible for you to make a small repo that reproduces this error? When dealing with things like webpack, vue and others it's usually a problem with configuration files that depcheck can't read.

Cheers.

**Comment by tiagoppinho** [comment]
Well, you can see the project itself and test it! 

Here is the [project](https://github.com/ist-dsi/fenixedu-id-cards), to test the depcheck you will have to go to the Frontend component available at `src/main/frontend`.

Cheers.

**Comment by rumpl** [comment]
Nice! Gotta love open source! :)

**Comment by rumpl** [comment]
@tiagoppinho This is hopefully fixed with my PR, will release a new version and you can tell me if it fixes stuff for you.

Cheers!

**Comment by tiagoppinho** [comment]
@rumpl Thanks! Will update this issue once that PR gets merged and I test it on the project.

**Comment by rumpl** [comment]
I just pushed the 0.8.2 tag, it will soon be available on npm

**Comment by tiagoppinho** [comment]
After testing it on the project I think this issue is resolved. If I see some other problem I'll report it creating another issue.

Thanks!
