### ISSUE TITLE
Parse imports in *.less files

### ISSUE THREAD

**Issue by jrnail23** [depcheck/depcheck#380]
### Feature request description
Parse imports in *.less files

### Any extra info
I'll probably submit a PR myself for this, but I wanted to get it on the radar.

**Comment by rumpl** [comment]
@jrnail23 still want to work on this one?

**Comment by MickeyKay** [comment]
I see it's marked as `wontfix`, however flagging that I've run into the same issue recently and am +1 for considering a solution if possible. Thanks!

**Comment by rumpl** [comment]
Want to open a PR @MickeyKay ? :)

**Comment by jrnail23** [comment]
It's all yours, @MickeyKay.  Sorry I let this go stale -- I ended up just moving on and haven't had the need to go back.
