### ISSUE TITLE
false report on dependency

### ISSUE THREAD

**Issue by sarthak-gp** [depcheck/depcheck#401]
i see a lot of mistakes in the dependency report generated from depcheck.

**Comment by LinusU** [comment]
Your issue doesn't contain anything actionable for us. Can you provide which packages are marked incorrectly, and how they are marked?

**Comment by sarthak-gp** [comment]
The angular core dependencies and bootstrap are also coming up in the
report, which obviously shouldn't be the case.

**Comment by LinusU** [comment]
> [...] which obviously shouldn't be the case.

Can you please post your `package.json` and the output from the tool?
