### ISSUE TITLE
eslint-plugin-depcheck

### ISSUE THREAD

**Issue by idan-at** [depcheck/depcheck#403]
Hey!
Have you ever considered creating an eslint plugin that uses depcheck?
can be useful to add it on lint step instead of another step.

I guess it will have a single rule that enforces dependencies+devDependencies, and some options to reflect the command line arguments it currently receives.

wdyt?

**Comment by lijunle** [comment]
Parts of the depcheck is covered by this eslint plugin:
https://www.npmjs.com/package/eslint-plugin-import

Idan Attias <notifications@github.com> 于 2019年7月25日周四 00:11写道：

**Comment by idan-at** [comment]
I want to enforce that all modules written in my package.json (either `dependencies` or `devDependencies`) are used.
which rule should I use?

**Comment by lijunle** [comment]
This is not covered by any eslint rule. It is a rule of depcheck -
understand how each dependency in package.json are used. Maybe @rumpl has
some ideas.

Idan Attias <notifications@github.com> 于 2019年7月28日周日 00:26写道：

**Comment by idan-at** [comment]
Found this discussion on `eslint-plugin-import`: https://github.com/benmosher/eslint-plugin-import/issues/877, which talks exactly about that.
