### ISSUE TITLE
show react jsx file by 

### ISSUE THREAD

**Issue by shacoshe** [depcheck/depcheck#405]
### Feature request description
A description of the feature request

### Code snippets (if applicable)
How the dependency is used (if applicable):

```
code snippet here
```

How the dependency is listed in package.json (if applicable):

```
package.json snippet here
please include the section name (e.g. devDependencies, dependencies)
```

### Any extra info
Anything else you want to include. Thank you for your input!

**Comment by rumpl** [comment]
What?
