### ISSUE TITLE
option --json changes return status

### ISSUE THREAD

**Issue by mrbobfrog** [depcheck/depcheck#407]
### Bug Description
On a code base, when I run `depcheck <project> --json` it changes the return status (returns zero on unused or missing dependencies). FYI `depcheck <project>` returns non-zero.

### Code snippets
Where the dependency is used:

```
var http = require('http');

var server = http.createServer(function(req, res) {
  res.writeHead(200);
  res.end('Hi everybody!');
});
server.listen(8080);
```

Where the dependency is listed in package.json:

```
{
  "name": "simple",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "typescript": "~3.4.5"
  }
}
```

### Versions
 - `node -v`: v10.16.0
 - `npm -v`: 6.10.3
 - `depcheck --version`: 0.8.3

### Extra info

I would like to use `depcheck` as part of an automated build pipeline. Unfortunately, it does not behave consistently when I use the `--json` option.

Here's my test:
```
$ depcheck .
Unused dependencies
* typescript
$ echo $?
255
$ depcheck . --json
{"dependencies":["typescript"],"devDependencies":[],"missing":{},"using":{},"invalidFiles":{},"invalidDirs":{}}
$ echo $?
0
```

BONUS POINTS: If you wish to help us debug further, the `depcheck --json` option will show more information. Check [here in the README](https://github.com/depcheck/depcheck#example) for documentation on json output.

**Comment by rumpl** [comment]
@mrbobfrog Thanks for reporting this, will be fixed in the next release, see #465
