### ISSUE TITLE
Load ignore rules from a lines separated file

### ISSUE THREAD

**Issue by Urik** [depcheck/depcheck#409]
### Feature request description
Would be very nice being able to load ignore rules from a lines separated file in addition to the "--ignores" flag.  
This would make it possible to source control the ignores rules, and simplify CI pipelines. 

### Any extra info
Already have a PR for this feature:
https://github.com/depcheck/depcheck/pull/408

**Comment by VincentLanglet** [comment]
This would be great

**Comment by znarf** [comment]
@rumpl This can be closed.

**Comment by rumpl** [comment]
At your service :)
