### ISSUE TITLE
False Alert for "fs"

### ISSUE THREAD

**Issue by AbdulHannan96** [depcheck/depcheck#412]
fs node package false alert in my task. I am using fs in many lines for handling files but depcheck marks it as unused which is quite surprising.

**Comment by rumpl** [comment]
Do you define fs as a dependecy in your package.json?

**Comment by rumpl** [comment]
“fs” is a core node module and shouldn’t be added in the package.json file

**Comment by AbdulHannan96** [comment]
yeah It is defined in my package.json. I am new at using node and typescript so I was not aware of this. Even if it should not be there, why is depcheck pointing it out as an unused dependency ?

**Comment by LinusU** [comment]
> why is depcheck pointing it out as an unused dependency 

Because when you are doing `require('fs')` you are not requiring that package, but rather the built-in `fs` package. Thus the package installed to `node_modules/fs` is, in fact, unused ☺️

**Comment by rumpl** [comment]
We should maybe have a more explicit error message for the core modules...

I'm closing this one 

Cheers
