### ISSUE TITLE
readme.md missing instructions

### ISSUE THREAD

**Issue by joshuambg** [depcheck/depcheck#416]
### Bug Description
```
$ sudo npm install -g depcheck
$ depcheck
$
```
Nothing happens? 
```
$ rm -rf node_modules/
```
Now it works. Why does the node_modules folder have to be removed? If that's a requirement it should be specified in the readme.

### Versions
 - `node -v`: v10.16.0
 - `npm -v`: 6.9.0
 - `depcheck --version`: 0.8.3

**Comment by rumpl** [comment]
Hey @joshuambg 

It's indeed weird that depcheck doesn't say anything, at least it should say: `No depcheck issue`. 

Could you rerun it like this: `decheck --json` and give me the output.

**Comment by znarf** [comment]
It's actually the opposite, some features are not working properly if `node_modules` is missing.
