### ISSUE TITLE
Depcheck should only process files that are relevant to depcheck

### ISSUE THREAD

**Issue by mzyil** [depcheck/depcheck#420]
### Bug Description
depcheck processes irrlevant files too, there is not any filter about it.

For example huge irreleavant files and then gives an error complaining their size. It should not read them at all.

In our case when there is a core dump file about 2 GBs depcheck starts reading that file and the operating system (Ub 18) kills it (it writes `Killed`) because of it's memory usage. I guess it also reads the file several times because the memory usage goes up to 12 GBs, my machine has 16 GB of ram btw.

Interestingly enough if the file size is too big (e.g. 5-10 GB) node itself gives an error about reading it instead. 

### Code snippets
Where the dependency is used:

```
irrelevant
```

Where the dependency is listed in package.json:

```
irrelevant
```

### Versions
 - `node -v`: v8.14.0
 - `npm -v`: 6.9.0
 - `depcheck --version`: 0.8.0-alpha.3

### Extra info
Depending on the ram usage sometimes you do not get the `Killed` message and depcheck finishes successfully. Ramping up the ram usage through opening several programs (multiple tabs in Chrome?) helps to replicate the issue.

BONUS POINTS: If you wish to help us debug further, the `depcheck --json` option will show more information. Check [here in the README](https://github.com/depcheck/depcheck#example) for documentation on json output.

**Comment by mzyil** [comment]
It would be a better solution if there were an option to process only certain file extensions.

**Comment by znarf** [comment]
This should be solved by https://github.com/depcheck/depcheck/pull/513

**Comment by znarf** [comment]
Can be closed now that https://github.com/depcheck/depcheck/pull/513 is merged.

**Comment by rumpl** [comment]
Thanks, check your emails :)
