### ISSUE TITLE
body-parser

### ISSUE THREAD

**Issue by aneesshameed** [depcheck/depcheck#423]
Why does depcheck alert false, saying that body-parser is not installed while express installs it as a dependency?

**Comment by rumpl** [comment]
@aneesshameed could you please give me more info, the template had all the information that we need to help you :
```
---
name: Bug report
about: Create a report to help us improve

---

### Bug Description
A description of the bug

### Code snippets
Where the dependency is used:

```
code snippet here
```

Where the dependency is listed in package.json:

```
package.json snippet here
please include the section name (e.g. devDependencies, dependencies)
```

### Versions
 - `node -v`:
 - `npm -v`:
 - `depcheck --version`:

### Extra info
Any extra info you want to include. Thank you for the bug report!

BONUS POINTS: If you wish to help us debug further, the `depcheck --json` option will show more information. Check [here in the README](https://github.com/depcheck/depcheck#example) for documentation on json output.
```

**Comment by aneesshameed** [comment]
Sorry, this was opened by mistake, I then read the documentation a few more times. My mistake, sorry

**Comment by rumpl** [comment]
Cool!

If you have any ideas as to how we could make the documentation better, feel free to tell us :)
