### ISSUE TITLE
Does not provide valid results if the angular app is build with Nrwl

### ISSUE THREAD

**Issue by vikas2future** [depcheck/depcheck#426]
### Bug Description
When i run a depcheck against an angular app built using nrwl (https://nx.dev/angular) , it does not indentify the dependencies correctly

Nrwl is based on the concept of monorepos , where you can have multiple apps referring to multiple libs. This will enable us to share more code amongst the apps.

Issue:  depcheck utility is unable to find the libraries that an app is dependent on. Hence it shows erroneous report of unused dependencies.

### Code snippets
Where the dependency is used:

```
code snippet here
Ran depcheck on the root folder

Where the dependency is listed in package.json:

```
package.json snippet here
  "dependencies": {
    "@angular/animations": "^8.2.4",
    "@angular/cdk": "^8.2.0",
    "@angular/common": "^8.2.4",
    "@angular/compiler": "^8.2.4",
    "@angular/core": "^8.2.4",
    "@angular/flex-layout": "^8.0.0-beta.26",
    "@angular/forms": "^8.2.4",
    "@angular/material": "^8.2.0",
    "@angular/platform-browser": "^8.2.4",
    "@angular/platform-browser-dynamic": "^8.2.4",
    "@angular/router": "^8.2.4",
    "@angular/service-worker": "^8.2.4",
    "@asymmetrik/ngx-leaflet": "^4.0.0",
    "@auth0/angular-jwt": "^2.1.2",
    "@ngrx/effects": "8.3.0",
    "@ngrx/entity": "^8.1.0",
    "@ngrx/router-store": "8.3.0",
    "@ngrx/store": "8.3.0",
    "@ngrx/store-devtools": "^8.1.0",
    "@ngx-pwa/local-storage": "^8.2.1",
    "@ngx-translate/core": "^10.0.2",
    "@ngx-translate/http-loader": "^3.0.1",
    "@nrwl/angular": "^8.4.13",
    "@scwx/theme": "file:libs/theme",
    "@swimlane/ngx-charts": "^12.0.1",
    "@swimlane/ngx-datatable": "^15.0.2",
    "@swimlane/ngx-graph": "^6.1.0",
    "@types/moment-timezone": "^0.5.12",
    "@webcomponents/custom-elements": "^1.2.4",
    "ag-grid-angular": "^21.2.2",
    "ag-grid-community": "^21.2.2",
    "angular-calendar": "^0.26.11",
    "angular-gridster2": "^8.1.0",
    "angular-in-memory-web-api": "^0.9.0",
    "angular-tree-component": "^8.4.0",
    "angular2-counto": "^1.2.5",
    "angular2-query-builder": "^0.3.3",
    "angularx-qrcode": "^1.6.4",
    "apollo-angular": "^1.7.0",
    "apollo-angular-link-http": "^1.8.0",
    "apollo-cache-inmemory": "^1.6.3",
    "apollo-client": "^2.6.4",
    "apollo-link": "^1.2.13",
    "apollo-link-error": "^1.1.12",
    "auth0-js": "^9.11.2",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.6.9",
    "cytoscape": "^3.8.1",
    "d3-geo-projection": "^2.7.0",
    "date-fns": "^1.30.1",
    "file-saver": "^2.0.2",
    "graphql": "^14.5.6",
    "graphql-tag": "^2.10.1",
    "hammerjs": "^2.0.8",
    "highlight.js": "^9.15.9",
    "install": "^0.12.2",
    "intl": "^1.2.5",
    "jison": "^0.4.18",
    "leaflet": "^1.5.1",
    "leaflet-arc": "^1.0.2",
    "leaflet-map": "^0.2.1",
    "libphonenumber-js": "^1.7.22",
    "lorem-ipsum": "^2.0.3",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.26",
    "msal": "^1.0.2",
    "ng-event-source": "^1.0.14",
    "ng-mocks": "^8.1.0",
    "ng2-dragula": "^2.1.1",
    "ngx-markdown": "^8.1.0",
    "ngx-moment": "^3.4.0",
    "ngx-pagination": "^3.3.1",
    "ngx-perfect-scrollbar": "^6.3.1",
    "ngx-quill": "^7.2.0",
    "npm": "^6.10.1",
    "otp-client": "^1.0.1",
    "quill": "^1.3.6",
    "rxjs": "^6.5.2",
    "stream": "0.0.2",
    "timers": "^0.1.1",
    "uuid": "^3.3.2",
    "web-animations-js": "^2.3.2",
    "webcola": "^3.4.0",
    "webdriver-manager": "^12.1.7",
    "xml2js": "^0.4.19",
    "zone.js": "^0.9.1"
  },
"devDependencies": {
    "@angular-devkit/build-angular": "^0.802.2",
    "@angular-devkit/build-ng-packagr": "^0.802.2",
    "@angular/cli": "^8.3.4",
    "@angular/compiler-cli": "^8.2.4",
    "@angular/language-service": "^8.2.4",
    "@ngrx/schematics": "8.3.0",
    "@nrwl/builders": "^7.0.2",
    "@nrwl/jest": "^8.5.0",
    "@nrwl/nx": "^7.8.7",
    "@nrwl/schematics": "^8.5.2",
    "@nrwl/workspace": "8.5.0",
    "@types/chai": "^4.1.7",
    "@types/chai-as-promised": "^7.1.0",
    "@types/cucumber": "^4.0.7",
    "@types/d3": "^4.13.2",
    "@types/hammerjs": "^2.0.36",
    "@types/jasminewd2": "^2.0.6",
    "@types/jest": "^24.0.9",
    "@types/leaflet": "^1.4.7",
    "@types/node": "^12.7.4",
    "chai": "^4.2.0",
    "chai-as-promised": "^7.1.1",
    "codelyzer": "^5.0.1",
    "crypto": "^1.0.1",
    "cucumber": "^5.1.0",
    "cucumber-html-reporter": "^4.0.5",
    "cypress": "^3.4.1",
    "cypress-commands": "^0.2.0",
    "d3": "^4.13.0",
    "dotenv": "6.2.0",
    "fs-extra": "^7.0.1",
    "http-server-spa": "^1.3.0",
    "husky": "^3.0.5",
    "jest": "^24.1.0",
    "jest-preset-angular": "^7.0.0",
    "lite-server": "^2.5.3",
    "ls": "^0.2.1",
    "mocha": "^5.2.0",
    "mochawesome": "^4.1.0",
    "mochawesome-merge": "^2.0.1",
    "mochawesome-report-generator": "^4.0.1",
    "ng-packagr": "^5.4.0",
    "npm-run-all": "^4.1.5",
    "prettier": "1.18.2",
    "pretty-quick": "^1.11.1",
    "protractor": "^5.4.2",
    "protractor-cucumber-framework": "^6.1.3",
    "protractor-http-client": "^1.0.4",
    "protractor-multiple-cucumber-html-reporter-plugin": "^1.8.1",
    "rimraf": "^3.0.0",
    "ts-node": "^8.3.0",
    "tsickle": "^0.37.0",
    "tslib": "^1.10.0",
    "tslint": "~5.9.1",
    "tslint-config-prettier": "^1.18.0",
    "typescript": "~3.5.3",
    "webpack-bundle-analyzer": "^3.3.2",
    "yargs": "^12.0.5"
  }
please include the section name (e.g. devDependencies, dependencies)
```

### Versions
 - `node -v`: 12.9.1
 - `npm -v`: 6.10.2
 - `depcheck --version`: 0.8.3

### Extra info
Any extra info you want to include. Thank you for the bug report!
The app folder structure is like below:

root
     apps
            app-name
     libs
         lib-1
         lib-2
         lib-3
package.json


BONUS POINTS: If you wish to help us debug further, the `depcheck --json` option will show more information. Check [here in the README](https://github.com/depcheck/depcheck#example) for documentation on json output.
depcheckoutput
[depcheckoutput.txt](https://github.com/depcheck/depcheck/files/3713817/depcheckoutput.txt)

.json

**Comment by mhamri** [comment]
I have the same issue , any solution for this?

**Comment by dommyboy** [comment]
bump
