### ISSUE TITLE
12x more useful if Missing dependencies includes the file it was found it

### ISSUE THREAD

**Issue by twk-b** [depcheck/depcheck#428]
### Feature request description
i have a list of Missing dependencies, and i want to know what should be investigated, excluded, or otherwise

### Expected output
$ depcheck
Missing dependencies
fred: ./src/yourfile.js line 4
james: ./dist/whocars.js line 29,999

### Any extra info
pure awesome

**Comment by LinusU** [comment]
That would be nice 👍

**Comment by rumpl** [comment]
@twk-b Wanna do it? It sure could be 12x (at least) more useful!

**Comment by twk-b** [comment]
[428.diff.txt](https://github.com/depcheck/depcheck/files/3785968/428.diff.txt)

* doesnt have line counts
* syntax loads in VScode to load correct file
* shows relative path
