### ISSUE TITLE
check packages for: final socre, maintainers, liecense, hasTests, downloads, deps, popularity, maintenance

### ISSUE THREAD

**Issue by twk-b** [depcheck/depcheck#434]
### Feature request description
when checking deps in package.json 

I care about:

* number of maintainers
* License
* npm scores
    * final score (npm) 
    * popularity 
    * maintenance
* maintainers
* hasTestScripts - if package.json has npm run test configured properly
* number of downloads 
* number of deps that package has
* number of dependents
* test no engines.node require higher then package.json as minimum (MISSING)

depcheck --withNpmRemoteCalls [--deep]
* --deep options to go into packages recursively
shows list of packages with this information
│ module                       │ final │ maintainers │ license      │ hasTestScripts │ downloads │ deps  │ dependents │ popularity │ maintenance │ fail │
│ tough-cookie-filestore@0.0.1 │ 1.657 │ ONE!      │ MIT          │ MISSING        │ 1         │ 51    │ 221        │ 1.131      │ 0.000       │ FAIL │
│ generate-schema@2.6.0        │ 4.397 │ ONE!      │ MIT          │ true           │ 2         │ 47    │ 2286       │ 2.602      │ 1.992       │      │

maybe formatted more similar to npm audit, instead of as table

fails on:
* hasTestScripts = false is always a fail
* no license is always fail

configurable fails on
* minimum maintainers, popularity final score, number of downloads
* configurable list of licenses

### Code snippets (if applicable)
How the dependency is used (if applicable):

```
const {Command, flags} = require('@oclif/command');
var path = require('path');
var request = require('request');
var _ = require('lodash');
var Table = require('cli-table');

class PackageCheckCommand extends Command {
  async run() {
    const {flags} = this.parse(PackageCheckCommand);
    const name = flags.name || 'world';
    var filename = path.join(process.cwd(), 'package.json');
    this.log(filename);
    var packageJson = require(filename);
    var keys = Object.keys(packageJson.dependencies);

    var log = this.log;

    request({
      method: 'post',
      url: 'https://api.npms.io/v2/package/mget',
      json: keys
    }, function (err, response, body) {
      if (err) {
        this.error('err', err);
        process.exit(1);
      } else {
        var packageCheckJson = _.sortBy(body, 'score.final');
        var table = new Table({
          head: ['module', 'final', 'matainers', 'license', 'hasTestScripts', 'downloads', 'deps', 'dependents', 'popularity', 'maintenance', 'fail']
        });

        var fail;
        _.forEach(packageCheckJson, function (module) {
          fail = module.score.final < 0.1 || !module.collected.metadata.license || !module.collected.metadata.hasTestScript;

          table.push([
            module.collected.metadata.name + '@' + module.collected.metadata.version || 'unknown',
            (module.score.final * 10).toFixed(3),
            (module.collected.metadata.maintainers.length > 1 ? module.collected.metadata.maintainers.length : 'ONE!'),
            module.collected.metadata.license || '',
            module.collected.metadata.hasTestScript || 'MISSING',
            Object.keys(module.collected.metadata.dependencies || []).length,
            module.collected.npm.dependentsCount || '0',
            module.collected.npm.downloads[0].count || 'NONE',
            (module.score.detail.popularity * 10).toFixed(3),
            (module.score.detail.maintenance * 10).toFixed(3),
            fail ? 'FAIL' : ''
          ]);
        });
        log(table.toString());
      }
    });
  }
}

PackageCheckCommand.description = 'check package.json file';

PackageCheckCommand.flags = { };

module.exports = PackageCheckCommand;
```

How the dependency is listed in package.json (if applicable):

```
{ "depcheck": { "withNpmRemoteCalls": true, "min": { "final": 4, "maintainers": 2 } "licensees": ["MIT", "BSD"] } }
```

**Comment by twk-b** [comment]
to me this is the next level of checks that need to be done on deps so it belongs here.

I think lots of devs have similar second level tests they are running, centralizing those would be good.

* stale / last updated should totally be on the list (online/audit)
* testing for licenses - many companies need this (offline)
* engine would be a nice addition 8,10,12,13 (offline)

depcheck is used in two modes:
* developer looking forward, what should be fixed, like npm audit
* offline / ci mode - engine/license tests would still be good

move visibility to packages without: more then one maint, without tests, without license etc, would help clean up the eco system.

getting packages to clean up deps vs devDeps to counts down also would be dreamy.

**Comment by VincentLanglet** [comment]
> Hey, this is something I [wanted to build 4 years ago](https://github.com/rumpl/stale-deps), I'm not sure this kind of features would be useful for depcheck, it should exist, but maybe in another package. WDYT?

I think this could be a great feature, but this should be another package.
This is clearly not the same behaviour to parse all the files to find if the dependency is use, and to check online if the dependencies are still alive.
