### ISSUE TITLE
Node modules may be in parent directories

### ISSUE THREAD

**Issue by sveyret** [depcheck/depcheck#436]
### Bug Description
When using the `bin` special parser, the binary module is only looked in current project `node_modules` folder. But actually, node may also search the module in parent folders. See https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders

This feature is especially mostly used by yarn workspaces or lerna monorepo.

### Versions
 - `node -v`: any
 - `npm -v`: any
 - `depcheck --version`: 0.8.4

### Extra info
I already did the correction in my system and will provide a PR. I've just seen that PR #418 seems to give a correction to it, but it is introducing new dependencies while my correction only adds a few lines to bin.js.

**Comment by rumpl** [comment]
Closed by #437
