### ISSUE TITLE
TypeScript: false positive for node built-in module types

### ISSUE THREAD

**Issue by sveyret** [depcheck/depcheck#444]
### Bug Description
In TypeScript, when using built-in modules, we can import the typing definition named `@types/node`. Unlike other `@types` imports, this one does not use the module name, it is a single typing module for all built-in modules.
For that reason, this typing module is not detected as used.

### Code snippets
Where the dependency is used:

```
import * as path from 'path';
```

Where the dependency is listed in package.json:

```
"devDependencies": {
  "@types/node": "12.11.7"
}
```

### Versions
 - `node -v`: any
 - `npm -v`: any
 - `depcheck --version`: 0.8.4

### Extra info
I will provide a PR.

**Comment by rumpl** [comment]
PR merged, closing this thanks
