### ISSUE TITLE
special/webpack: entries should also be scanned

### ISSUE THREAD

**Issue by sveyret** [depcheck/depcheck#446]
### Bug Description
In the `entry` section of webpack configuration, we may also specify dependencies which should be scanned. It is the case, for example, of the @babel/polyfill, of special fonts, etc.

### Code snippets
Where the dependency is used:

```
module.exports = {
  entry: [
    '@babel/polyfill',
    'typeface-roboto',
    './src/index.ts',
    './src/images/favicon.png'
  ]
}
```

Where the dependency is listed in package.json:

```
"dependencies": {
  "typeface-roboto": "0.0.75"
},
"devDependencies": {
  "@babel/polyfill": "7.6.0",
}
```

### Versions
 - `node -v`: v8.12.0
 - `npm -v`: 6.4.1
 - `depcheck --version`: 0.8.4

### Extra info
I am currently working on a PR for this issue.

**Comment by rumpl** [comment]
Closed with #449
