### ISSUE TITLE
False positive depcheck

### ISSUE THREAD

**Issue by VincentLanglet** [depcheck/depcheck#460]
Depcheck is reporting himself as unused dependency.

**Comment by rumpl** [comment]
Need more info please

**Comment by VincentLanglet** [comment]
If you run yarn add depcheck and yarn depcheck, it reports depcheck as unused. But I’am using it with my command...

**Comment by VincentLanglet** [comment]
Oh, it seems adding this
```
{
  "script": {
    "depcheck": "depcheck",
  }
}
```
in the `package.json` fixed the issue.

The strategy for the binary is not optimal

**Comment by rumpl** [comment]
When you add those lines in your package.json it tells depcheck that you will use that dependency when running some npm command. If you add a dependency that is used as a binary but you don't add it anywhere then there is no way for us to know if it's used or not, I prefer to say that it isn't. I mean they could have some script somewhere that does something like `./node_modules/.bin/depcehck` to call it but the way I see it it's better to use npm scripts for this kind of things. Makes sense?

**Comment by VincentLanglet** [comment]
I understand you cant know if it's used or not, except if there is a line about it in the package.json.

I was think about a special case for the library you're using using.
If you run `yarn depcheck` it should not say `depcheck` is unused.
If you run `yarn npm-check` it should not say `npm-check` is unused.

But it's just a little improvement which is maybe difficult to implement and then not worth it.

**Comment by rumpl** [comment]
Ok it's actually quite easy, I just had to understand what you were saying, PR opened

**Comment by rumpl** [comment]
Scratch that, it's not that simple, I'll continue on this tomorrow

**Comment by VincentLanglet** [comment]
@rumpl Did you find a solution ? :)

**Comment by VincentLanglet** [comment]
Hi @rumpl  ! Happy new year !

Did you find a solution ? :)
