### ISSUE TITLE
Packages used inside package.json are not detected

### ISSUE THREAD

**Issue by ktalebian** [depcheck/depcheck#461]
I'm using [husky](https://github.com/typicode/husky), but when I run `depcheck` it doesn't recognize `husky` and labels it as unused:

```bash
$ depcheck
Unused dependencies
* husky
```

Same goes for `ts-node` that I use as `"test": "nyc mocha -r ts-node/register $(find test -name '*.ts')",`

`depcheck` does not complain about `nyc` being unused but also does not detect it as missing if I do not install it. Looks like packages that are used inside `package.json` file either as a hook or as part of a script are not recognized.

**Comment by rumpl** [comment]
Hey @ktalebian 

Husky detection landed today! https://github.com/depcheck/depcheck/pull/453

It will be available in the next release, sometimes next week.

**Comment by rumpl** [comment]
Could you open a new issue for ts-node, nyc please?
