### ISSUE TITLE
install fails with yarn

### ISSUE THREAD

**Issue by jmjpro** [depcheck/depcheck#471]
### Bug Description
When installing from yarn `yarn global add depcheck` I receive the following error:
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "12.13.0"

Ironic that depcheck requires nodejs > 10 but one of it's dependencies doesn't work with nodejs > 9.

The workaround is to install with `yarn global add depcheck --ignore-engines` but this can cover up other problems.

### Versions
 - `node -v`: 12.13.0
 - `npm -v`: N/A
 - `depcheck --version`: N/A

**Comment by rumpl** [comment]
Hey @jmjpro thanks for reporting this. 

Our dependencies are up to date but not those of our dependencies :(

I'll try to find which one is it and fix this.
