### ISSUE TITLE
False positives between 0.8.3 - 0.8.4

### ISSUE THREAD

**Issue by 43081j** [depcheck/depcheck#472]
With 0.8.4, my entirely typescript codebase results in most of my dependencies being detected as unused with no changes other than bumping depcheck. This must mean we've introduced either a bug or a breaking change somewhere.

I call it like so:

```ts
  depcheck(
    __dirname,
    {
      ignoreDirs: ['dist', 'test'],
      ignoreMatches: [
        '@types/*',
        '@webcomponents/*',
        'tslib'
      ]
    },
    resolve
  );
```

(I dont remember why I have those `ignoreMatches`, they havebeen there a long time)

The most obvious change between 0.8.3 and 0.8.4 was that babel is used for typescript now rather than typescript its self, so i suspect this came from that change.

It may be that I'm doing something wrong, _however_ it does mean 0.8.4 was still a breaking change as my only local change has been to update that.

I'll continue investigating meanwhile

cc @rumpl

**Comment by rumpl** [comment]
Hey @43081j 

Could you try with 0.9.0?

**Comment by 43081j** [comment]
👋 

I tried it in 0.9.0 first, thats where i saw the problem. So i then went to 0.8.4 to see if it was introduced by that or later.. so it seems 0.8.4 introduced it. Narrows it down a bit at least

**Comment by rumpl** [comment]
Care to share the output with 0.8.3 and 0.9.0? Ideally the --json one

**Comment by 43081j** [comment]
Strangely the parser never seems to get called for the files containing the missing dependencies.

If I breakpoint inside `parseTypescript`, it only gets hit for a small amount of files, a whole bunch don't pass through.

ill post the json if i get chance

**Comment by 43081j** [comment]
@rumpl i think i tracked it down.

basically its because when someone switched the parser to babel, they unknowingly also dropped the tsconfig-driven feature set for a hard-coded one we define [here](https://github.com/depcheck/depcheck/blob/dcb186fd0bd4df535b10223b5908dca708acc6e3/src/parser/typescript.js#L9).

in my case (and probably the majority of broken cases) it is decorators.

typescript uses a different decorator spec to babel.

in the past, this wasn't a problem because typescript had them turned on in tsconfig and they disappeared before they reached babel.

however, now they do reach babel and it doesn't have the legacy decorator plugin enabled when transpiling.. so we get a whole boat load of these errors (which btw also get eaten up and never thrown):

```
SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (199:2)
```

**Comment by rumpl** [comment]
Good catch! 

It’s about time typescript support was a first class citizen, I’ll try to find some time tomorrow and do it properly
