### ISSUE TITLE
special/eslint: bad calculation of preset dependencies

### ISSUE THREAD

**Issue by sveyret** [depcheck/depcheck#476]
### Bug Description
In a monorepo project managed by `yarn`, I have a package containing my eslint configuration. Every eslint needed dependency is set as a dependency (not dev!) of this package.

This is currently working because of 2 bugs, one masking the other:

- the method `requireConfig` of `eslint.js` only searches for configuration dependency in the current directory, therefore ignoring structures like yarn workspaces; it should use the new `utils.loadMetadata` function to use the real node resolution mechanism;
- when analyzing `eslint` configuration dependencies, it does not look at this dependencies' dependencies.

In a normal environment (if I had a configuration package apart), the process would fail because it would be able to analyse the project configuration file, see that a lot of packages are needed, but not see that they already are integrated because dependencies of this configuration package, so displaying a lot of “missing dependencies”.

### Code snippets
**In the package `@my-project/eslint-config`:**

File `.eslintrc.yaml`:

```yaml
plugins:
  - react-hooks
```

File `package.json`:

```json
  "dependencies": {
    "eslint-plugin-react-hooks": "2.2.0"
  }
```

**In the package `@my-project/other-package`**

File `.eslintrc.yaml`:

```yaml
extends:
  - '@my-project'
```

File `package.json`:

```json
  "devDependencies": {
    "@my-project/eslint-config": "0.0.1"
  }
```

**Execution**

In the directory of `other-package`:

    depcheck --specials=eslint

**Expected result**

No error.

**Actual result**

- with a yarn workspace, no error because hoist `eslint-config` is not seen by the analyzer;
- with npm and lerna, `missing dependencies: eslint-plugin-react-hooks` because the analyzer sees the `eslint-config` but does not read its included dependencies.

### Versions
 - `node -v`: 12.13.0
 - `npm -v`: 6.12.0
 - `yarn -v`: 1.19.1
 - `depcheck --version`: 0.9.1

### Extra info
Sorry for not publishing a PR, but I can't really spend more time on `depcheck`.

**Comment by rumpl** [comment]
Thanks for reporting

I'm not sure I understand everything, in particular the "Actual result", could you tell me what command you are running and from which directory?

**Comment by sveyret** [comment]
I edited the initial post. Command executed from `other-package`:

    depcheck --specials=eslint

**Comment by sveyret** [comment]
To be more precise, with yarn workspace, `other-package` lies in `./packages/other-package` from the root of the project. There is a directory `node_modules` in `./packages/other-package` containing only a few dependencies and a `.bin` sub-directory with links to binaries. All other dependencies are in a directory `node_modules` which is directly in the root of the project.

With `npm` used as if all packages where separated projects, all dependencies directly are on `node_modules` in the `other-package` folder.

With `lerna link`, it is almost the same as with `npm`, except that local monorepo dependencies are direct links to their local directories.

**Comment by sveyret** [comment]
Finally, I'm working on it… :smile:

**Comment by rumpl** [comment]
🎉

I'll buy you a beer next time you come to Paris :)
