### ISSUE TITLE
Support .*ignore files

### ISSUE THREAD

**Issue by znarf** [depcheck/depcheck#497]
I think it would be useful to implement support for ".*ignore" files as an alternative to the `ignore-dirs` option. See for example what was done in prettier: https://github.com/prettier/prettier/issues/2294 and https://github.com/prettier/prettier/pull/2412

Pros:

- Most projects already have a `.gitignore` file and this could be automatically used. I don't think anyone wants do `depcheck` any paths ignored in `.gitignore`. I've seen `depcheck` crashing because it was not ignoring some of these files (in my case, huge binary files >= 100MB), it was difficult to troubleshoot.
- The syntax used in `.gitignore` and similar `.ignore` files is more powerful than the current `ignore-dirs` API. It allows using `glob` while the `ignore-dirs` API is only expecting exact matches on single level directory names. https://github.com/depcheck/depcheck/blob/master/src/check.js#L144

Cons:
- It's confusing to introduce duplicate functionality with `ignore-dirs` and an incompatible syntax. There needs to be a sensible transition strategy.

**Comment by rumpl** [comment]
+100 for an ingore file, we can have both for some time and print a warning to say that the flag will be deprecated (we already had a deprecated flag, when I removed it 2+ years later no one complained.

**Comment by znarf** [comment]
@rumpl would be great to to look at my PR!

**Comment by znarf** [comment]
Implemented.
