### ISSUE TITLE
False alert for babel package

### ISSUE THREAD

**Issue by icco** [depcheck/depcheck#499]
I ran dep check in github.com/icco/writing and got the following output:

```
$ yarn run depcheck .
yarn run v1.19.1
$ /Users/nat/Projects/writing/node_modules/.bin/depcheck .
Unused dependencies
* @opencensus/instrumentation-all
* babel-plugin-graphql-tag
* immutable
* prop-types
Unused devDependencies
* depcheck
* webpack
```

I am using `babel-plugin-graphql-tag` in my babel config.

**Comment by znarf** [comment]
@icco can you link to your project ? Or share the name of your babel config file and it's content?

**Comment by icco** [comment]
Yup! https://github.com/icco/writing/blob/c803380b7fbb340f117523aceb2bfebc709c3155/.babelrc.js

**Comment by znarf** [comment]
Interesting, I don't have the same result here:

```
Unused dependencies
* @opencensus/instrumentation-all
* babel-plugin-transform-define
* immutable
* prop-types
Unused devDependencies
* webpack
Missing dependencies
* expect-ct: ./server.js
```

**Comment by icco** [comment]
Ah, it's on an unmerged branch, `rewrite-apollo`. Altho in the case of master, I'm also using `babel-plugin-transform-define` and it's saying it's unused.

**Comment by znarf** [comment]
@icco When testing on `rewrite-apollo`:
- can't reproduce the `babel-plugin-graphql-tag` warning
- `babel-plugin-transform-define` is not in your babel config so it's right to say it's unused.
