### ISSUE TITLE
Yarn workspace root dependencies not found

### ISSUE THREAD

**Issue by pushred** [depcheck/depcheck#509]
Not sure that #473 is working as expected, at least with Yarn workspaces. I'm using depcheck@0.9.1 installed in the root of my monorepo where various dev dependencies are also installed. I run depcheck within each package using a npm script:

```
../../node_modules/.bin/depcheck .
```

However I have some missing dependencies reported, for example:

```
{
  "dependencies": [],
  "devDependencies": [],
  "missing": {
    "timekeeper": [
      "/Users/example/dev/frontend/packages/helpers/getAge.test.js"
    ]
  },
  "using": {
    "lodash": [
      "/Users/example/dev/frontend/packages/helpers/apportionValues.js",
      "/Users/example/dev/frontend/packages/helpers/getUniqueId.js"
    ],
    "d3-format": [
      "/Users/example/dev/frontend/packages/helpers/formatCurrency.js"
    ],
    "luxon": [
      "/Users/example/dev/frontend/packages/helpers/formatDate.js",
      "/Users/example/dev/frontend/packages/helpers/getAge.js",
      "/Users/example/dev/frontend/packages/helpers/getAge.test.js"
    ],
    "timekeeper": [
      "/Users/example/dev/frontend/packages/helpers/getAge.test.js"
    ],
    "nanoid": [
      "/Users/example/dev/frontend/packages/helpers/getUniqueId.js"
    ]
  },
  "invalidFiles": {},
  "invalidDirs": {}
}
```

#473 uses [require.resolve](https://nodejs.org/api/modules.html#modules_require_resolve_request_options) but it's still scoped to specified root dir / CWD rather than allowing [actual node module resolution](https://nodejs.org/api/modules.html#modules_all_together) to happen, which includes parent dirs. Yarn Workspaces and Lerna especially rely on this behavior to share ["hoisted" dependencies](https://github.com/lerna/lerna/blob/master/doc/hoist.md) between packages. This is a big part of their appeal.

If I run this in a REPL:

```
require.resolve('timekeeper')
```

… I see:

```
/Users/example/dev/frontend/node_modules/timekeeper/lib/timekeeper.js'
```

Also `/Users/example/dev/frontend/package.json` specifies it as a dev dependency.

**Comment by sveyret** [comment]
Just for information, the path given to `require.resolve` is the start of the search. Node is also searching in parent directories.
