### ISSUE TITLE
Use Cosmiconfig

### ISSUE THREAD

**Issue by sveyret** [depcheck/depcheck#516]
The `Cosmiconfig` project (https://github.com/davidtheclark/cosmiconfig) is a library used to standardize configuration files. It is currently used by some tools like `prettier`. I think that one day, it would be mandatory to have this library as a dependency in order to correctly find the dependencies' configuration. So maybe that's a good idea to take and use it for `depcheck`.

Yes, I know you've just worked to add configuration file management to `depcheck`, but as no release has been made since, it is probably a good idea to look at this now.

**Comment by rumpl** [comment]
;) https://github.com/depcheck/depcheck/pull/408

**Comment by sveyret** [comment]
I should have had a look at the source before writing… ;)

**Comment by rumpl** [comment]
No worries :)
