### ISSUE TITLE
Missing Changelog for 0.9.2

### ISSUE THREAD

**Issue by stnwk** [depcheck/depcheck#521]
Hi :)

Thanks for your work on this package!

Unfortunately, upgrading from 0.9.1 to 0.9.2 suddenly reports a lot of invalid files, but I'm not really sure why or what to look for as there currently is no changelog for 0.9.2

Can you please add it and let everyone know what changed?
Thanks!

**Comment by rumpl** [comment]
Hey, sorry about that, will update the changelog in a couple of minutes.

Could you show me the output of `depcheck --json` please?

**Comment by rumpl** [comment]
Here you go: https://github.com/depcheck/depcheck/releases/tag/0.9.2

Again, sorry about that, I need to make this less manual...

**Comment by rumpl** [comment]
Could you open a new issue with the problem you are seeing with the 0.9.2 please, it would mean a lot
