### ISSUE TITLE
PeerDependencies -> unused library

### ISSUE THREAD

**Issue by meriturva** [depcheck/depcheck#522]
Is it possible to add here returns about unused libraries present on peerDependencies?

https://github.com/depcheck/depcheck/blob/19f9dadcfa728d77ea6943e368ba0a949ccd6594/src/check.js#L239

Actually, we are developing angular libraries and it is a good practice to use peerDependencies:
https://angular.io/guide/creating-libraries#use-typescript-path-mapping-for-peer-dependencies

**Comment by meriturva** [comment]
Just found a really easy workaround useing result object `unused.using`:

```
const packageFile = require(path.join(packagePath, 'package.json'));
const packagePeerDependenciesUsedNames = Object.keys(packageFile.peerDependencies);
const realAllDependenciesUsedNames = Object.keys(unused.using);
const peerDependenciesUnused = packagePeerDependenciesUsedNames.filter(item => realAllDependenciesUsedNames.indexOf(item) < 0);
```

**Comment by rumpl** [comment]
Hey @meriturva 

I'm not sure I completely understand your use case, we are looking at peer dependencies.

Could you make a small repo that reproduces your use case please?

**Comment by meriturva** [comment]
Thanks @rumpl for your answer:

I just would like to have also:

`peerDependencies: lodash.difference(peerDeps, usingDeps),`

on: https://github.com/depcheck/depcheck/blob/19f9dadcfa728d77ea6943e368ba0a949ccd6594/src/check.js#L239

**Comment by meriturva** [comment]
The request is still valid.
Thanks.

**Comment by chrisbobbe** [comment]
> use case

I think `rumpl` is asking you to clarify the use case. What are you trying to do, that you can't do with `depcheck` in its current state? That's a different question from "How should `depcheck` be changed?" 🙂
