### ISSUE TITLE
Please consider using confinode

### ISSUE THREAD

**Issue by sveyret** [depcheck/depcheck#523]
Yes, I know, I wrote an issue suggesting using _cosmiconfig_ a few weeks ago… But because I did not have the same philosophical view as the author, I created my own library for this job. And of course, I think it is better! :wink: 
Whether you use it or not, I'd really appreciate to know why, this would help me to improve my work. And of course, if you have questions or need help about this library, do not hesitate and ask!

**Comment by rumpl** [comment]
Hey, will take a look at confinode :)

**Comment by sveyret** [comment]
Thank you @rumpl, and if you want me to make a PR to integrate it, do not hesitate and ask me…

**Comment by sveyret** [comment]
Hey, any news on this?
