### ISSUE TITLE
Typescript dependencies with format @types/xxxx are incorrectly reported when using type imports

### ISSUE THREAD

**Issue by izaera** [depcheck/depcheck#526]
I have `@types/estree` in my `package.json` and a `.ts` which does:

```typescript
import ESTree from 'estree';
```
This is the correct syntax, since `tsc` complains if you import from the `@types` scope.

In this case, `depcheck` complains about missing dependency `estree`.

**Comment by sveyret** [comment]
If your file importing `estree` is named with a `.ts` extension, _depcheck_ will use the _TypeScript_ parser. Then, for each imported module, it will consider the `@types` version of the module potentially used. So you shouldn't have this issue. Actually, if _depcheck_ complains for missing `estree`, it means that you did not add `estree` to your dependencies in your `package.json`.

**Comment by mickdekkers** [comment]
> if depcheck complains for missing estree, it means that you did not add estree to your dependencies in your package.json.

I imagine this is true for most packages, but we've run into an exception where adding the non-`@types` module to the dependencies wouldn't make sense: the [`@types/aws-lambda` package](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/aws-lambda). This package [describes the types](https://serverlessfirst.com/fff-aws-lambda-type-definitions/) of the [AWS Lambda](http://docs.aws.amazon.com/lambda) runtime environment. This package is purely compile-time so there is no run-time dependency to import.*

I see issue #568 has been opened for this, so I'll just link to that for anyone else coming from Google.

\* There does exist a package named [`aws-lambda`](https://github.com/awspilot/cli-lambda-deploy) but this unrelated to the `@types` package.

**Comment by sveyret** [comment]
I also faced this problem with a few packages for which I needed to import the `@types` while not using the runtime library. IMHO, these are exceptions that I simply add in the ignore configuration entry of `depcheck`.

I did not find a generic way to treat this, but would be happy if someone has an idea.

**Comment by clar-cmp** [comment]
I feel like checking for `import type` would be a good way to allow importing `@types/*` dependencies instead.
