### ISSUE TITLE
babelrc format

### ISSUE THREAD

**Issue by zb140** [depcheck/depcheck#527]
`.babelrc` files are actually JSON5 rather than plain JSON, meaning (among other things) that they can have comments in them (see https://babeljs.io/docs/en/config-files).  Unfortunately since `depcheck` uses `JSON.parse`, it will fail to parse files that take advantage of JSON5 features, leading to false positives.  Would you consider adding support for these JSON5 files?

**Comment by zb140** [comment]
I still think it's worth considering this. It would make it much less frustrating to use depcheck-based tools with projects built with Babel.

**Comment by rumpl** [comment]
@zb140 I just opened a PR for this, if all goes well it will be available in the next relase. 

Cheers

**Comment by zb140** [comment]
@rumpl that's excellent, thank you!
