### ISSUE TITLE
ignore-patterns option from readme description is not supported in latest release

### ISSUE THREAD

**Issue by SkReD** [depcheck/depcheck#537]

**Comment by znarf** [comment]
True, master was not released yet on npm.

@rumpl Time for `0.10.0` or `1.0.0`? Changes are too significant to be released as patch.

**Comment by rumpl** [comment]
Go for 1.0.0, i believe you have the rights Francois? It should be as easy as creating and pushing a tag, the ci will then publish on npm and creat a release on github.

**Comment by znarf** [comment]
@rumpl I don't think I have the rights. I need:

- push access to master on `GitHub` (updating changelog and other chore)
- publish access on `npm` https://www.npmjs.com/~znarf

**Comment by rumpl** [comment]
No need for an access on npm, publishing on npm is done automatically when a tag is pushed. I’ll be home is ~1h, let’s do that then if you have the time. 

Come to the francejs slack community, I hang there a lot

**Comment by znarf** [comment]
@rumpl I'll try to move forward with that in the coming days.

**Comment by znarf** [comment]
It's released now. Thank you @rumpl
