### ISSUE TITLE
--dev=false not working

### ISSUE THREAD

**Issue by defaultbr** [depcheck/depcheck#538]
Hello, i'm passing the flag `--dev=false` but it keep breaking the run because there is some devDependencies not used.

Since its some serverless plugins, even its use in serverless, its says that are not used, of course, it doesnt parse the yaml.

The problems is that the flag is not working :|

**Comment by znarf** [comment]
Could you give detailed steps on how to reproduce? On which project are you testing? What is happening and what were you expecting?

**Comment by acnghm** [comment]
I think this is the same issue I see when there are dependencies listed in `./serverless.yml` under the [plugins key](https://www.serverless.com/framework/docs/providers/aws/guide/plugins/).

Running `depcheck --json .` gives:
```
{
  "dependencies": [],
  "devDependencies": [
    "serverless-domain-manager",
    "serverless-offline",
    "serverless-s3-remover"
  ],
  "missing": {},
  "using": {
    // omitted for brevity
  }
}
```
Package.json `devDependencies` looks like:
```
"devDependencies": {
    "eslint": "^6.6.0",
    "eslint-config-airbnb-base": "^14.1.0",
    "eslint-config-prettier": "^6.7.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-prettier": "^3.1.1",
    "jest": "^24.9.0",
    "jest-dynalite": "^1.1.6",
    "jest-watch-typeahead": "^0.4.2",
    "prettier": "^1.19.1",
    "serverless": "^1.55.1",
    "serverless-domain-manager": "^3.3.0",
    "serverless-offline": "^5.12.0",
    "serverless-s3-remover": "^0.6.0"
  }
```

`Serverless.yml` contains (amongst other things):
```
plugins:
  - serverless-domain-manager
  - serverless-offline
  - serverless-s3-remover
```

Platform:
```
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G5033

npm --version
6.14.4

node --version
v12.18.0

depcheck --version
0.9.2
```

From looking at the docs it looks like this is the kind of thing a "special component" does. 

Regarding the above comment, I'm unsure what `--dev=false` does but `depcheck --ignores="serverless*" gives me `No depcheck issue` which is what I expect.
