### ISSUE TITLE
Support webpack config that exports a possibly async function

### ISSUE THREAD

**Issue by mightyiam** [depcheck/depcheck#539]
https://webpack.js.org/configuration/configuration-types/#exporting-a-function

https://github.com/depcheck/depcheck/blob/8228da293f61085e001a68e59912c38a921e9e79/src/special/webpack.js#L163-L168

**Comment by znarf** [comment]
Please provide an example repository so people can see the use case more clearly.

**Comment by mightyiam** [comment]
@znarf it is explained in the first link in the description, under "exporting a function". That should suffice.

**Comment by znarf** [comment]
@mightyjam it's easier if there is an example repository. Without that, I will personally not look at it.
