### ISSUE TITLE
depcheck should ignore hidden folders and files

### ISSUE THREAD

**Issue by ddbhagat** [depcheck/depcheck#543]
I don't see depcheck is ignoring hidden folders like `.circleci` or `.history`. Now `.history` holds the local versioning of files in vscode. and errors are marked against those files. Please validate

**Comment by rumpl** [comment]
Hey,

You can use `--ignore-patterns` when invoking `depcheck` or create a [configuration file for it](https://github.com/depcheck/depcheck#usage-with-a-configuration-file)

**Comment by ddbhagat** [comment]
@rumpl I did try few patterns with --ignore-patterns but none of them really worked for me. Not to mention i did follow gitignore specs as well

**Comment by rumpl** [comment]
@ddbhagat could you please show us an example of your setup and how you are running depcheck?

**Comment by ddbhagat** [comment]
So I was trying ignore-patterns, but that looks to be not working at all. i can see another bug for it. So I did try below

`ignore-dirs: ["assets", "config", "dist", "docs", "__mocks__", "node_modules", ".*"]`

and other variances like .*/ etc. 
Only one thins works for hidden history folder is

`ignore-dirs: ["assets", "config", "dist", "docs", "__mocks__", "node_modules", ".history"]`

**Comment by rumpl** [comment]
Ok so this seems fixed in master:

```bash
$ ls -lRa
total 16
drwxr-xr-x   5 djordjelukic  wheel  160 Jun  5 16:00 .
drwxrwxrwt  10 root          wheel  320 Jun  5 16:05 ..
drwxr-xr-x   3 djordjelukic  wheel   96 Jun  5 16:01 .test
-rw-r--r--   1 djordjelukic  wheel   29 Jun  5 16:00 index.js
-rw-r--r--   1 djordjelukic  wheel  230 Jun  5 16:00 package.json

./.test:
total 8
drwxr-xr-x  3 djordjelukic  wheel   96 Jun  5 16:01 .
drwxr-xr-x  5 djordjelukic  wheel  160 Jun  5 16:00 ..
-rw-r--r--  1 djordjelukic  wheel   24 Jun  5 16:01 index.js

$ node bin/depcheck.js
Missing dependencies
* colors: ./index.js
* r: ./.test/index.js

$ node bin/depcheck.js --ignore-patterns=".*"
Missing dependencies
* colors: ./index.js
```

So it will be available once it's published, should be soon, @znarf wana publish 1.0.0 ?

**Comment by znarf** [comment]
@rumpl I'll try to move forward with that in the coming days.

**Comment by znarf** [comment]
`--ignore-patterns`and `--ignore-path` should work properly from `1.0.0`
