### ISSUE TITLE
Missing dependencies highlighted incorrectly for file paths

### ISSUE THREAD

**Issue by ddbhagat** [depcheck/depcheck#544]
Missing dependencies highlighted incorrectly for file paths
For some of the below imports which resolve to ingternal files 

```
import { someAction } from "connectors/SomeConnector";
import someOtherAction from "src/someOtherWorker";
```
 What we see in depcheck output
```

**Missing dependencies**
* connectors: ./src/Abc.tsx
* src: ./src/Abc.tsx
* components: ./src/Abc.tsx
* shared: ./src/Abc.tsx
* reducers: ./src/Abc.tsx
```

**Comment by rumpl** [comment]
I'm not sure I understand, what's the output you expected for this?

**Comment by ddbhagat** [comment]
Essesntially those are not packages but the file paths. And the depcheck highlighting the folder names as missing dependencies.

**Comment by rumpl** [comment]
depchck doesn't know and will never handle things like this.

My guess is you added some webpack configuration to make this possible, we have no way of knowing what your webpack configuration looks like for real. 

Also I presonally think this is a bad practice, just use relative paths for your local code.

**Comment by ddbhagat** [comment]
These are relative file paths only. And depcheck is picking package names as missing package. I am currently exclusing them using `ignore` option.

**Comment by rumpl** [comment]
These
```javascript
import { someAction } from "connectors/SomeConnector";
import someOtherAction from "src/someOtherWorker";
``` 

are not relative path, these are:
```javascript
import { someAction } from "./connectors/SomeConnector";
import someOtherAction from "./src/someOtherWorker";
```

**Comment by ddbhagat** [comment]
Unfortunately this doesnt solve the issue form me.

**Comment by rumpl** [comment]
Could you please be more specific?
