### ISSUE TITLE
TS types are outdated in 1.0.0

### ISSUE THREAD

**Issue by VladimirGrenaderov** [depcheck/depcheck#558]
No ignorePatterns in options, etc.

**Comment by rumpl** [comment]
Thanks for reporting this. Care to open a PR? :)

**Comment by VladimirGrenaderov** [comment]
Not yet ) I see some work is in progress, let's wait for readme update. 

Offtopic: great tool, but it can't be used in real ci/cd process with large codebase. As an example, you have to choose between custom ignore file and .gitignore - why not both? It's impossible to pass custom specials via command line (or config), etc. I may participate this project as contributor, but in general it's need to rewrite depcheck on TS :)

**Comment by rumpl** [comment]
What do you mean by "can't be used with large codebases"? Because it's slow?

I'm not sure why you are talking about a .gitignore file.

You can give it custom specials when used as a library, not when you call it from the cli, I would be willing to merge a PR that adds this functionality but we would need to talk about the best way to implement it.

Rewriting the tool in TS is not something I look forward to, there is too much code and I don't have enough time.

**Comment by VladimirGrenaderov** [comment]
Let me explain in details. 

- .gitignore: imagine a large monorepo, with a number gitignored dirs (test & coverage reports, various caches, etc). But also it has some dirs (scripps, some build system staff doesn't directly used as 'dependencies'). As a user, I want to respect my large .gitignore file AND other stuff. But I can't - depcheck will use only one ignore file. Welcome wrapper which reads custom ignore file, adds it content to ingorePatterns and allows depcheck to use .gitignore fallback. It's one of my cases.

- customs specials. Yes, I mean stupid wrapper to pass specials to depcheck instead of use some kind of config or long line in ppackage.json.

One of my responsibilities - ci/cd process in a large team. "Linter-nazi", in other words - all that can be verified must verified. Sadly, monorepos with top-level node modules allows to make a lot mistakes (yarn 2.0 shall fix it - but both TS & vscode teams rejects proposals from **acranis**, one by one). Depcheck with homemade specials is a solution.

So, let me prepare couple of PRs - to fix bin special (bug with scoped packages, as far as I remember), add tsconfig special, etc. TS is a bit far perspective, agree.
