### ISSUE TITLE
False unused dev dependencies report 

### ISSUE THREAD

**Issue by billyjov** [depcheck/depcheck#560]
Running `npx depcheck` inside an Angular CLI Project and `karma` and related dependencies was reported as unuse

**Comment by rumpl** [comment]
Awesome, is that on a pristine new angular cli project?

**Comment by billyjov** [comment]
No. It's an existing project with Angular CLI version 9

**Comment by rumpl** [comment]
A tiny bit more information would be very useful. 

I am going to close this issue, feel free to open a new one and please use the template provided
