### ISSUE TITLE
depcheck plugins

### ISSUE THREAD

**Issue by rumpl** [depcheck/depcheck#562]
Openning this to start a conversation about a plugin system for depcheck, see [this comment](https://github.com/depcheck/depcheck/pull/559#pullrequestreview-444523729).

We have a lot of specials in our codebase and need to add a new one each time we need to do something special for a new tool/framework/library. The nice thing about this is that all you need to do (in an ideal world) is to execute `depcheck` and not worry about what plugin you need. The less nice thing is that we have a lot of code to maintain and we don't always know really how to use the thing in the first place, see the serverless PR linked above.

We could have way less code with a real pluggable mechanism and we could depend on the community to write plugins for depcheck. This comes with a cost for the users and us too: 
* we need to be really careful when we change our public API
* users will need to configure depcheck before using it - this could be done in a nice way: `depcheck init` that will interactively setup the depcheck configuration.

How would you see the plugin system in depcheck ?

**Comment by znarf** [comment]
That could start with a refactor, moving the core of `depcheck` in `depcheck-core` (npm package), moving specials in `depcheck-plugin-babel`, `depcheck-plugin-eslint`, `depcheck-plugin-prettier`, etc. We would keep `depcheck` as a bundle of `depcheck-core` + all the current plugins as dependencies.

I think we can take some inspiration of the `eslint` plugin system. There would be some programmatic way to require the plugin and constructing the config in JavaScript but we should also keep a simple way to enable these plugins using JSON based configuration `{"plugins": ["babel", "eslint", "prettier]}` or CLI `depcheck --plugins=babel,eslint,prettier`.
