### ISSUE TITLE
depcheck should ignore depcheck by default

### ISSUE THREAD

**Issue by craftmaster2190** [depcheck/depcheck#565]
Kind of funny:

```
Unused devDepenedecies:
* depcheck
```

Expected behavior:
depcheck should ignore depcheck by default

**Comment by rumpl** [comment]
Yes but what of you don’t really use depcheck? ;)

How do you use it in your codebase?

**Comment by craftmaster2190** [comment]
`npx depcheck`

**Comment by rumpl** [comment]
Ok so you don’t need depcheck in your dependencies
