### ISSUE TITLE
False positive: core-js

### ISSUE THREAD

**Issue by clar-cmp** [depcheck/depcheck#567]
With `@babel/preset-env` required and the `babel` special used, `core-js` shows up as an unused dependency. This is actually required for polyfills to work.

**Comment by yathishc** [comment]
+1,
Same issue here

**Comment by rumpl** [comment]
Reading the documentation [here](https://babeljs.io/docs/en/babel-preset-env) and they don't really say that you need to install `core-js` with `preset-env`, could you create a sample repository that shows that `preset-env` **needs** `core-js`?

**Comment by clar-cmp** [comment]
Reading that exact documentation says otherwise: https://babeljs.io/docs/en/babel-preset-env#usebuiltins

**Comment by rumpl** [comment]
Ooh I didn’t see that, thanks. 

So the answer is, as always, “it depends” and we need to be smart and look at the usebuiltins flag. 

Thanks! Will try and fix this as soon as I get some time, PRs are more than welome :)

**Comment by clar-cmp** [comment]
Didn't actually realise it was conditional until I read more closely, since I've always used that flag. Sorry for not being clear

**Comment by rumpl** [comment]
No worries, it’s all clear now, thanks for reporting this. Progress is slow I know, we support too many tools that have too many edge cases and there aren’t enough hours in a day :)

**Comment by clar-cmp** [comment]
No worries, thank you for taking the time to work on this! :)

**Comment by clar-cmp** [comment]
Still an issue, it just takes a while. :)
