### ISSUE TITLE
False positive: types-only dependencies

### ISSUE THREAD

**Issue by clar-cmp** [depcheck/depcheck#568]
Specific example: `@types/aws-lambda` is included to ease writing AWS lambda handlers, although `aws-lambda` is *not* included. The import is also specifically an `import type` in the code to further clarify that this is a type-only import.

This is showing up as `aws-lambda` being a missing dependency when it actually isn't.

**Comment by clar-cmp** [comment]
Still a problem.

**Comment by clar-cmp** [comment]
Still a problem

**Comment by clar-cmp** [comment]
Still a problem

**Comment by vaclav-stummer** [comment]
Still a problem for the devDependecy `"@types/geojson": "7946.0.8",`

**Comment by TehShrike** [comment]
After bumping from TypeScript 4 to TypeScript 5, I ran into this issue.


With `depcheck@1.4.3`, `mysql2` is being marked as not used in a project with this reference to the package:
```ts
import type { Connection as MysqlConnection } from 'mysql2/promise'
```
