### ISSUE TITLE
wrong repo link in published module

### ISSUE THREAD

**Issue by gtanner** [depcheck/depcheck#57]
https://www.npmjs.com/package/depcheck

![screen shot 2015-11-19 at 4 12 18 pm](https://cloud.githubusercontent.com/assets/317051/11284545/5adedade-8ed8-11e5-8b2a-efc369a5ee2d.png)

**Comment by lijunle** [comment]
Thanks for reporting. I have fixed this in [package.json](https://github.com/depcheck/depcheck/blob/master/package.json#L11). However, because no new version is published to npm, the info in npm is not changed yet.

**Comment by lijunle** [comment]
Version 0.5.10 is published, link is updated.
