### ISSUE TITLE
False alert for dependecy by babel preset

### ISSUE THREAD

**Issue by emanuelb** [depcheck/depcheck#574]
content of `babel.config.js` is

```javascript
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
};
```

To reproduce:
1. Download https://github.com/MohGovIL/hamagen-react-native/archive/v2.2.6.zip
2. unzip file, cd "hamagen-react-native-2.2.6", Run `npx depcheck`
Result:
```
Unused dependencies
* @react-native-community/cli
* @react-native-community/masked-view
* @react-navigation/bottom-tabs
* @react-navigation/routers
* events
* logkitty
* lottie-ios
* moment-timezone
* random-location
* react-native-reanimated
* react-native-safe-area-context
* react-native-uuid-generator
* rn-fetch-blob
* seedrandom
* sha256
Unused devDependencies
* @babel/core
* @babel/runtime
* @react-native-community/eslint-config
* @types/jest
* @types/react-native-sqlite-storage
* @types/react-native-uuid-generator
* @types/react-test-renderer
* @types/seedrandom
* @typescript-eslint/eslint-plugin
* @typescript-eslint/parser
* babel-jest
* cross-fetch
* eslint
* eslint-import-resolver-reactnative
* eslint-plugin-import
* eslint-plugin-jsx-a11y
* eslint-plugin-react
* jest
* metro-react-native-babel-preset
* mock-async-storage
* react-test-renderer
* typescript
```

The `metro-react-native-babel-preset` is needed, without it the app won't compile
https://github.com/MohGovIL/hamagen-react-native/issues/173

**Comment by znarf** [comment]
What does `module` mean in `module:metro-react-native-babel-preset`? I'm not aware of this syntax, would it work without?

**Comment by emanuelb** [comment]
> What does module mean in module:metro-react-native-babel-preset? I'm not aware of this syntax, would it work without?

I don't know the answer to both of them, but this syntax is used in other projects as well for various babel configuration files:
https://github.com/facebook/react-native/blob/5218932b13ad0649ff2a57aaf1ec682fe278c47d/template/babel.config.js
https://github.com/facebook/jest/blob/master/examples/react-native/.babelrc.js

and here with other preset `module:react-native-dotenv` in file `.babelrc`
https://stackoverflow.com/questions/52621531/couldnt-find-preset-modulereact-native-dotenv

**Comment by rumpl** [comment]
[From here](https://babeljs.io/docs/en/options#name-normalization):

```
Any identifier prefixed with module: will have the prefix removed but otherwise be untouched.
```

Wow, that's... I'm speechless :D

**Comment by znarf** [comment]
Thank you @rumpl! So, @emanuelb, feel free to:

1) remove it in your codebase as it doesn't do anything, relic of the past perhaps. Then check that depcheck works if you remove it?
2) If presets are otherwise properly parsed, contribute a patch to depcheck and normalize the preset names by removing `module:`.
