### ISSUE TITLE
Can't read property 'name' of undefined

### ISSUE THREAD

**Issue by redevill** [depcheck/depcheck#579]
Not a good start for me:
Versions: Latest npm 6.14.8 and versions of node 10 & 12 were tried. Version 1.2.0 of depcheck
Setup: Installed depcheck globally per the documentation.
(Side note: Tried to verify with depcheck --v per standard - addition of this shortcut would be nice)

Running depcheck in the folder with the package.json produced:
"Can't read property 'name' of undefined"

Running depcheck /mypath with a specific path produced:
"Can't read property 'name' of undefined"

Running depcheck -v produced:
"Can't read property 'name' of undefined"

Running depcheck --json produced:
"Can't read property 'name' of undefined"

So - it appears that getRCFileConfiguration function is running, despite the fact I did not request the --config option.
Inside this function there is an error thrown with error.mark.name... apparently error.mark is undefined.
Hope that this helps

Disappointed that your lib is DOA

**Comment by rumpl** [comment]
So sorry we disappointed you. 

Thank you for your issue, will take a look

**Comment by redevill** [comment]
Let me know if I can help.
