### ISSUE TITLE
False Alert when including dependency for its types

### ISSUE THREAD

**Issue by Freddixx** [depcheck/depcheck#582]
Hi 👋 ,

I am working on a project where I had to add three packages just for the sake of using their typescript types (which is the officially recommended way as of the time I am writing this). I know it's not a good practice, but there is no way around it for now.

The problem is that `depcheck` is obviously failing because of these unused dependencies and my gut is telling me there is no way of telling those apart. The upside is that the packages are only really required during dev-time since they are types. Hence, is there any way to exclude `devDependencies` from the check altogether? 

Maybe I didn't check the readme throughly enough, but it would be great if that feature existed.

Thanks!

**Comment by rumpl** [comment]
@Freddixx there was such a flag [but it was removed](https://github.com/depcheck/depcheck/pull/450) 

We should really have better support for typescript...

**Comment by Freddixx** [comment]
Just my luck then 🤷‍♂️ 😃 

Any chance that this could be brought back?

**Comment by rumpl** [comment]
[Will be there in the next release](https://github.com/depcheck/depcheck/pull/595), tomorrow surely :)

**Comment by rumpl** [comment]
Adding proper TS support is something I wanted to do for a long time, just never managed to gather the courage and the motivation, I hope I'll get to it one day. Sorry, I can't promise anything

**Comment by Freddixx** [comment]
I see. 

I didn't see that PR you mentioned linked to any issue but this one, so I don't know enough about the history why this got removed in the first place. But I guess you don't see any point in bringing it back, no?
