### ISSUE TITLE
False positive with roboto-fontface

### ISSUE THREAD

**Issue by AxopenLyon** [depcheck/depcheck#587]
I'm using `roboto-fontface` in my Angular/SCSS project, and even though I have an import from `roboto-fontface` package in my main SCSS, it says it's not used (I have the `node-sass` dependency for depcheck): 

`import '../node_modules/roboto-fontface/css/roboto/roboto-fontface.css';`

![image](https://user-images.githubusercontent.com/69004513/96695360-dc282d80-1389-11eb-8b72-6cb005922231.png)

**Comment by rumpl** [comment]
@AxopenLyon could you please make a repo that reproduces this error? Or at least give us the output of `depcheck --json` please?
