### ISSUE TITLE
False positive with tldts

### ISSUE THREAD

**Issue by nalham** [depcheck/depcheck#588]
I'm using [tldts](https://www.npmjs.com/package/tldts) in my Typescript project. Even after usage, it is showing the dependency as unused

Usage:
```
import { parse } from 'tldts';

...

const parsedUrl = parse(url);
```

Error:
![image](https://user-images.githubusercontent.com/25572315/96903050-2b359780-144a-11eb-8667-40ebc2fae47b.png)

**Comment by rumpl** [comment]
@nalham could you show us the result of `depcheck --json` please?
Or even better fill-in all these:


A description of the bug

### Code snippets

Where the dependency is used:

```
code snippet here
```

Where the dependency is listed in package.json:

```
package.json snippet here
please include the section name (e.g. devDependencies, dependencies)
```

### Versions

- `node -v`:
- `npm -v`:
- `depcheck --version`:

### Extra info

Any extra info you want to include. Thank you for the bug report!

BONUS POINTS: If you wish to help us debug further, the `depcheck --json` option will show more information. Check [here in the README](https://github.com/depcheck/depcheck#example) for documentation on json output.
