### ISSUE TITLE
Allow to define patterns against absolute file path (again)

### ISSUE THREAD

**Issue by Avaq** [depcheck/depcheck#589]
Hi! I'm opening this issue because it seems that the last time this issue was solved, the solution got lost at some point.

- Original issue: #107
- Solution: #108 
- Line in change log: https://github.com/depcheck/depcheck/blob/62640856028eea8192d9c89952dc37258ece0611/CHANGELOG.md#070-beta1-2016-03-10

The solution introduced most notably this change:

https://github.com/depcheck/depcheck/blob/98ad446cb84971d9362de807c3b41d69c6a11658/src/check.js#L123-L126

But on `main` and `master`, the change has gone missing, and the code still checks against the basename of files, making it impossible to have different parsers on different directories:

https://github.com/depcheck/depcheck/blob/adb216659b9f4d3ffe7e34fbae88d56e142ad090/src/check.js#L97-L103

Could it be that this change was lost when 0.7.0 was released? The change was part of 0.7.0-beta, and it seems there were some chronology issues during that time: https://github.com/depcheck/depcheck/issues/304

**Comment by Avaq** [comment]
I can find no evidence of the change having been reverted. In fact, the blame for the line on `master` is *older* than the merged changes, suggesting that the `master` branch was overwritten with a different history at some point.

**Comment by rumpl** [comment]
@Avaq thanks for this, I have no idea what happened, will investigate

**Comment by rumpl** [comment]
Version 1.3.0 with this change will soon be available on npm

**Comment by Avaq** [comment]
Thanks, I appreciate that! Is it not a breaking change though? I imagine patterns like `*.js` would no longer match any files (except those in the root of the file system). It may need to be released under a new major version so not to surprise users with a required change to their config files. Alternatively, I think you could fall back to testing on the basename for unmatched files to preserve backwards compatibility.. that might also be hazardous though.

**Comment by rumpl** [comment]
Indeed, but it's too late now, we'll see at what point I broke people, my guess is that it's not that much, I'm not sure a lot of people use this feature, I mostly see people running `depcheck` directly and some use the `ignores`, my guess would be that this broke a small subset of users.

Also, the fix for those  that this broke is quite minimal :)

**Comment by Avaq** [comment]
Alright, no worries then. Thanks for your work on this! :D
