### ISSUE TITLE
false alert for React 17

### ISSUE THREAD

**Issue by theKashey** [depcheck/depcheck#591]
React 17(babel plugin) does not requires "react" to be explicitly imported, which results in it being detected as an unused dependency.

**Comment by rumpl** [comment]
@theKashey thanks for openning the issue, would you have an example repo where I could reproduce the error?

**Comment by rumpl** [comment]
Ok so [reading from the blog](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) it would seem that there is no need to import React if:

* babel version is >= 7.9.0
* you are using `@babel/plugin-transform-react-jsx` 
* or if you are using `@babel/preset-react` with the `{"runtime": "automatic"}` option

To make things more interesting `{"runtime": "automatic"}` will be the default starting from version 8 of babel

**Comment by theKashey** [comment]
Absolutely correct. React is now just "automagic"

**Comment by rumpl** [comment]
> React is now just "automagic"

It always was :)

**Comment by rumpl** [comment]
Version 1.3.0 with this change will soon be available on npm
