### ISSUE TITLE
.depcheckrc not respected when running depcheck from a parent directory

### ISSUE THREAD

**Issue by jwarby** [depcheck/depcheck#592]
I'm trying to use depcheck in a monorepo project and have run into a minor issue. Given a project setup like this:

```
monorepo-project
└── packages
    └── a
        ├── .depcheckrc
        ├── node_modules
        ├── package.json
        └── yarn.lock
```

- If I run `npx depcheck` from inside `packages/a`, `.depcheckrc` is used - ignored dependencies from `.depcheckrc` are properly ignored
- If I run `npx depcheck packages/a` from the monorepo root, `.depcheckrc` is not used - it will report ignored dependencies as being unused

Happy to whip up a sample repository to demonstrate if needed! Thanks :)

**Comment by rumpl** [comment]
@jwarby thanks for reporting this, no need for a sample repo, the issue is cristal clear 👍

**Comment by jwarby** [comment]
Cool thanks @rumpl!

**Comment by BenJackGill** [comment]
Why was this closed?

Seems like the bot closed it incorrectly.

Would love to see a fix for this.
