### ISSUE TITLE
Depcheck Fails Incorrectly at "=" sign starting v1.3.0

### ISSUE THREAD

**Issue by SudharakaP** [depcheck/depcheck#601]
### Bug Description

It seems that starting v1.3.0 depcheck fails when it encounters an "=" sign in an import. The following line of code fails after upgrading to 1.3.0. 

https://github.com/opencollective/opencollective-frontend/blob/a07621f0d3e8e349bfb662df95cdfa305ca1b790/pages/marketingPage.js#L18

The error is;

```
Missing dependencies
* file-loader?publicPath=: ./pages/marketingPage.js
```
But with v1.2.0 there's no problem and depcheck seems to pass. 😄 

### Versions

- `depcheck --version`: 1.3.0

**Comment by SudharakaP** [comment]
Also just to note that it's the `=` sign that seems to trigger this. If there's no `=` sign in the import statement it seems to pass. 👍🏽

**Comment by rumpl** [comment]
Dang it!

Thanks @SudharakaP yes this is indeed a bug introduced with the latest version, I did change the webpack special, will fix asap

Thanks

**Comment by rumpl** [comment]
@SudharakaP fixed in https://github.com/depcheck/depcheck/pull/602 I tested with the opencollective frontend and it works, will merge and push a new version as soon as the PR is green, sorry about that.

**Comment by rumpl** [comment]
Version 1.3.1 should go live soon, tell me if this works for you

**Comment by SudharakaP** [comment]
@rumpl : Thanks a bunch for the quick response. Will let you know as soon as I verify it. 😄

**Comment by rumpl** [comment]
As soon as [this build finishes](https://travis-ci.org/github/depcheck/depcheck/builds/742565648) :)

**Comment by SudharakaP** [comment]
@rumpl : Issue fixed and verified. Therefore I am closing this. Thanks a bunch. 👍🏽
