### ISSUE TITLE
Not working with Vue3

### ISSUE THREAD

**Issue by The-Outrider** [depcheck/depcheck#610]
First and foremost, love this package, thank you for all your work on this.

### Bug Description

A description of the bug

When running depcheck it throws an error: "Vue packages version mismatch" 

- vue@3.0.2 (/Users/xxx/node_modules/vue/index.js)
- vue-template-compiler@2.6.12 (/Users/xxxx/node_modules/vue-template-compiler/package.json)

Vue3 doesn't use the template compiler anymore though. As mentioned here:

https://github.com/vuejs/vue-next/issues/670#issuecomment-579785869

### Versions

- `node -v`: 12.13.0
- `npm -v`: 6.13.1
- `depcheck --version`: 1.3.1

**Comment by hvitis** [comment]
Bumping up!

**Comment by rumpl** [comment]
👋 I just opened a PR https://github.com/depcheck/depcheck/pull/625

Can someone test that branch and tell me if it works? I don't really know vue... I added a test but I have no idea if the component I created is a vue 3 one

**Comment by rumpl** [comment]
@The-Outrider @hvitis ping nudge nudge :)

**Comment by The-Outrider** [comment]
I'll review later this afternoon (Europe time) ✌️ @rumpl

**Comment by The-Outrider** [comment]
I can confirm success! @rumpl Looks good!

**Comment by rumpl** [comment]
Woop woop let's goooo! 🎉

**Comment by rumpl** [comment]
I just released version 1.4.0 with this fix

**Comment by The-Outrider** [comment]
Awesome :) Thank you very much
