### ISSUE TITLE
Webpack config aliases marked as "Missing dependencies"

### ISSUE THREAD

**Issue by ugolb** [depcheck/depcheck#611]
### Bug Description

I have aliases in my webpack.config.js to make my import nicer.
When I run depcheck it marks couple of files as "Missing dependencies".
Interesting thing is that some aliases used in couple of different components but detected as missing only in one.

### Code snippets

webpack.config.js

```
      alias: {
        'components': path.resolve(__dirname, '../src/components'),
        'external-ui-components': path.resolve(__dirname, '../src/components/external/external-ui-components'),
        'constants': path.resolve(__dirname, '../src/utils/constants'),
        'external-icons': path.resolve(__dirname, '../src/components/external/external-icons'),
        'models': path.resolve(__dirname, '../src/models'),
        'services': path.resolve(__dirname, '../src/services'),
        'api': path.resolve(__dirname, '../src/api'),
        // Support React Native Web
        // https://www.smashingmagazine.com/2016/08/a-glimpse-into-the-future-with-react-native-for-web/
        'react-native': 'react-native-web',
        // Allows for better profiling with ReactDevTools
        ...(isEnvProductionProfile && {
          'react-dom$': 'react-dom/profiling',
          'scheduler/tracing': 'scheduler/tracing-profiling',
        }),
        ...(modules.webpackAliases || {}),
      },
```

### Versions

- `node -v`: v12.16.3npm -v

- `npm -v`: 6.14.5
- `depcheck --version`: 1.3.1

### Extra info
**Depcheck output:**

```
Missing dependencies
* components: .\src\App.jsx
* external-ui-components: .\src\App.jsx
* models: .\src\index.js
* api: .\src\services\LoginService.js
* external-icons: .\src\components\layout\passwordreset\password-reset.jsx
* services: .\src\components\layout\login\login-page.jsx
```

**Example of detected usage:**
![image](https://user-images.githubusercontent.com/14921564/99731526-4eda1500-2abe-11eb-9538-826143d1137d.png)

Example of not detected usage:
![image](https://user-images.githubusercontent.com/14921564/99731648-8052e080-2abe-11eb-83ec-02feaedefbd4.png)

Did I set something in wrong way?

**Comment by rumpl** [comment]
@ugolb please read the thread here https://github.com/depcheck/depcheck/issues/564
