### ISSUE TITLE
Support .js configuration files

### ISSUE THREAD

**Issue by CreativeTechGuy** [depcheck/depcheck#612]
### Feature request description

Support defining the configuration file in `.js` syntax. This is useful as it's the best file format to use for adding comments to a json object. Commenting why certain things are excluded or changed in a configuration file like this is very useful for future developers.

For some reason it's explicitly denied [here](https://github.com/depcheck/depcheck/blob/4024c04816eceed7ec847d974fa12f1302d554ed/src/utils/configuration-reader.js#L74) but I don't see any reason for why this was done in the comment or the PR it was added in. Nor do I see any comment in that PR which caused this change to be made. I'm simply requesting that this line is removed so we can use `.js` configuration files.

**Comment by rumpl** [comment]
See https://github.com/depcheck/depcheck/pull/518

**Comment by rumpl** [comment]
I’ll add a comment to the linked code though. Thanks :)

**Comment by WadePeterson** [comment]
Another reason for supporting `.js`config  files would be for extensibility of config files within a large project made up of multiple modules.

I am working in a large monorepo with multiple packages, and we have base configs for most tooling at the root, all using `.js` extensions. We currently do this for `jest`, `babel`, `webpack`, and `eslint`. This allows us to override specific things in individual modules that need them, and gives us the full power of Javascript to build the configs how we need them.

Supporting `.js` config files allows the consumer to build a custom extended config without the library having to define how "extending" a config happens (shallow merge? deep merge? what about arrays?). This is all very simple to do on the consumer side by just importing a JS object from one file, running some logic to build the extended object, and then exporting it. 

Here is a simple example of what I would like to do with `depcheck` (which is similar to we do on our project for all the above mentioned tools):

**my-repo/depcheck.config.js**
```js
/** @type {import('depcheck').Options} */
const options = {
  ignoreMatches: [
    'eslint*',
    'babel*'
  ]
}

module.exports = options
```

**my-repo/packages/module-a/depcheck.config.js**
```js
const baseOptions = require('../../depcheck.config.js')

/** @type {import('depcheck').Options} */
const options = {
  ignoreMatches: [
    ...baseOptions.ignoreMatches,

    // ignore some dependency module A handles on its own
    'some-other-module'
  ]
}

module.exports = options
```

I do realize this is all possible by creating a wrapper script that calls `depcheck` programmatically with a custom config, and that is likely what I will end up doing, but I feel like the CLI & js config option is a lot lighter weight on the consumer end.
