### ISSUE TITLE
Parse husky and lint-staged commands 

### ISSUE THREAD

**Issue by princed** [depcheck/depcheck#621]
### Feature request description

It would be convenient if `depcheck` could parse command of `husky` and `lint-staged` the same way it does with regular npm scripts. 

### How the dependency is used
For example, the following fragment of `package.json`
```json
  ...
  "husky": {
    "hooks": {
	  "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  },
  "lint-staged": {
    "*.{js,jsx,ts,tsx}": [
      "eslint --fix",
      "prettier --write"
    ],
    "*.{json,yml}": "prettier --write"
  }
  ...
```

would render packages `commitlint`, `eslint` and `prettier` as used.

**Comment by princed** [comment]
I' still d love to have this feature, but having the issue open doesn't change anything ¯\\\_(ツ)_/¯

**Comment by rumpl** [comment]
PRs are welcome
