### ISSUE TITLE
`Promise.all` fails in check.ts

### ISSUE THREAD

**Issue by joscha** [depcheck/depcheck#624]
### Bug Description

Big repositories seem to not be scannable:

```
RangeError: Too many elements passed to Promise.all
    at Function.all (<anonymous>)
    at ReaddirpStream.<anonymous> (/Users/joscha/.npm/_npx/58686/lib/node_modules/depcheck/dist/check.js:137:23)
    at ReaddirpStream.emit (events.js:321:20)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

unsure yet if it is the number of packages or number of dirs that causes this - the line numbers of the npx-installed `1.3.1` seem not to match https://github.com/depcheck/depcheck/blob/1.3.1/src/check.js

Update: seems to be readdirp-related, so maybe not the packages but the files.

### Code snippets

Where the dependency is used:

```
npx depcheck
```

### Versions

- `node -v`: v12.16.0
- `npm -v`: 6.14.8
- `npx depcheck --version`: 1.3.1

**Comment by rumpl** [comment]
Hey @joscha the limit seems to be `2097151` how big is your project?

**Comment by joscha** [comment]
Separate file descriptors in the folder I am running it on?

**Comment by rumpl** [comment]
Yes

**Comment by joscha** [comment]
```
find . -type f | wc -l
  461716
```
not even close to that number or am I holding it wrong?

**Comment by rumpl** [comment]
I'm guessing your repo is not open source?

**Comment by joscha** [comment]
Unfortunately not open source, yes the number I gave you includes node_modules and any other file in the folder even though that particular file type might not be introspected by the depcheck tool.
I can recount w/o node_modules if you like?
