### ISSUE TITLE
punycode being listed as unused, although the built in version is deprecated

### ISSUE THREAD

**Issue by ashward** [depcheck/depcheck#628]
### Bug Description

If the project includes `punycode` as a dependency in `package.json`, it gets listed as unused even when it's not.

This is because `punycode` is also included as a builtin in the Node API, but as it's been deprecated there since v0.7 it should now be included as an explicit dependency.

In fact, given that's it deprecated in the NodeJS API and has been for a long time, it might be helpful to list it as a missing dependency if it's used but hasn't been explicitly declared as a dependency in `package.json`.

See https://nodejs.org/api/punycode.html#punycode_punycode

**Comment by rumpl** [comment]
Nice catch! I didn't know about `punycode`. We are using the [builtin-modules module to filter out native node modules but sadly punycode is listed there](https://github.com/sindresorhus/builtin-modules/blob/HEAD/builtin-modules.json#L25).

Should be an easy fix, just need to find the time to do it.

Thanks

**Comment by rumpl** [comment]
Ok found some time :D

**Comment by ashward** [comment]
Thanks @rumpl. Stumped me for quite a while trying to work out why it was telling me that it was unused!
