### ISSUE TITLE
Svelte Support

### ISSUE THREAD

**Issue by kristianvld** [depcheck/depcheck#650]
### Feature request description

It would be nice to have support for svelte projects (raw Svelte, Sapper or SvelteKit projects), similar to the React and Vue support that exists currently.

### Any extra info

Currently when you run `depcheck` on a Svelte project, it reports imports used within `.svelte` files as unused. Have not tested with raw Svelte projects or SvelteKit, but assuming that it has problems interpreting the `.svelte` files.

**Comment by dedupely** [comment]
This would be great for us as well.
