### ISSUE TITLE
More examples (invocation, flags, and configs?)

### ISSUE THREAD

**Issue by tony** [depcheck/depcheck#651]
Hi, thank you for the project!  This seems very valuable!  I have a project that likely has many unused dependencies, but I'm not sure how to set up depcheck.

My project is a larger project using babel, typescript, webpack (with typescript webpack config), sass, eslint, etc. 

When searching, I have had a difficult time finding examples. StackOverflow, Medium, GitHub Issues, documentataion here itself - I see no examples of using depcheck on a large project.

### Feature request description

Provide examples of and make easily available:

- CLI Invocation
  - one or multiple `--parsers`
  - one or multiple `--specials`
  - one or multiple `--detectors`
- should webpack/babel/typescript/eslint point to babel, eslint, webpack config files? If so, what does it look like in CLI, in config file?
- Example of pointing to a dep check config (e.g. is their a `.depcheck.js` autodetected, or is `--config` always required?)
  - can configs be in  typescript?
- Example of integration with CI (e.g. GitHub actions?)

### Code snippets (if applicable)

I'm trying an example

```
npx depcheck --specials typescript,webpack,babel,prettier,eslint --parsers='.tsx:typescript' --parsers='.ts:typescript' ./
```

Output:

`(value || "").split is not a function`

I've googled for examples and can't find anything. I've found https://github.com/depcheck/depcheck/issues/246
 and it's closed.

### Any extra info

I think that people would benefit from seeing more examples of how to put depcheck into action, it's a mystery to me still! 😄

**Comment by tklltkioc** [comment]
I also think so.I need more examples, such as invocation, flags and configs.
