### ISSUE TITLE
False alert for package that is being used in "browserlist"

### ISSUE THREAD

**Issue by Avivhdr** [depcheck/depcheck#662]
False alert for package that is being used in "browserlist"

### Code snippets

Where the dependency is used (`packege.json`):
```
  "browserslist": [
    "extends @collibra/browserslist-config"
  ],
```

Where the dependency is listed in package.json:

```
  "devDependencies": {
    "@collibra/browserslist-config": "^1.0.0",

```

### Versions

- `node -v`: 16.4.2
- `npm -v`: 7.18.1
- `depcheck --version`: 1.4.2

### Extra info

![image](https://user-images.githubusercontent.com/23265867/128860090-6698d87e-77c2-4aea-9f54-4b4348806fee.png)

**Comment by jroru** [comment]
This issue still persists in depcheck@1.4.7
