### ISSUE TITLE
API is not usuable with bundler

### ISSUE THREAD

**Issue by zardoy** [depcheck/depcheck#676]
### Bug Description

https://github.com/depcheck/depcheck/blob/1c6efe2851b188d2c6bb24c5477c15692a1da2ed/src/constants.js#L5-L13

Please don't use dynamic requires here. Can we make them at compile time? My bundler isn't so smart, so it can't detect (and bundle) these imports. Because it isn't surrounded with try/catch, bundled code just crashes at runtime.

I suggest you to dynamically create `dist/parser/index.js` and `dist/detector/index.js` with all required imports, and in the code above just use namespace import.

## Steps to Reproduce

- Try to bundle code (I'm using esbuild for example)

### Versions

- `node -v`: v15.6.0
- `npm -v`: 7.4.0
- `depcheck --version`: 1.4.2

**Comment by rumpl** [comment]
PRs are more than welcome
