### ISSUE TITLE
Depcheck is reporting a false alert

### ISSUE THREAD

**Issue by mishra-animesh** [depcheck/depcheck#678]
When I am running, depcheck, it is reporting a false alert for some of the dependencies. Child_process being one of them.

Snip from depcheck

![image](https://user-images.githubusercontent.com/50451900/138697241-50e2464b-2b8e-4bc0-89d0-4172ada0f87f.png)

Snip from package.json

![image](https://user-images.githubusercontent.com/50451900/138697299-f275dc89-2884-49af-abea-408c14b55fb3.png)

Snip from usage:

![Untitled](https://user-images.githubusercontent.com/50451900/138698042-2df1d71b-e1b7-48da-b4ad-da1d92049d09.png)

Seeing this for other packages as well like fs,util.
Any idea why depcheck is reporting this as missed dependencies.

**Comment by s100** [comment]
When you do `import { execSync } from 'child_process'` that will import the [Node.js builtin](https://nodejs.org/api/child_process.html), not the [npm package](https://www.npmjs.com/package/child_process), which is useless. You can safely remove your production dependency on `child_process`. You should also update your import to state `import { execSync } from 'node:child_process'`, to reduce the ambiguity.
