### ISSUE TITLE
Support babel preset scope shorthand

### ISSUE THREAD

**Issue by dobesv** [depcheck/depcheck#719]
### Feature request description

In babel config, you can specify a preset as `@foo` and babel will search for a package named `@foo/babel-preset` instead.

**Comment by dobesv** [comment]
not stale

**Comment by miluoshi** [comment]
@rumpl Would you be up for reviewing it if I created a PR for this feature?

**Comment by rumpl** [comment]
Thanks! I’m on PTO, will be back in 10 days. Maybe @znarf can take a look while I’m gone
