### ISSUE TITLE
Support typescript "extends" and "types" fields

### ISSUE THREAD

**Issue by dobesv** [depcheck/depcheck#720]
### Feature request description

In TypeScript you can referenced your dependencies in the `extends` field, for example:

```
"extends": "@some/package/tsconfig.base.json"
```

or just

```
"extends": "@some/package"
```

So when processing typescript files we need to look into the `tsconfig.json` file and if we see an `extends` key we need to treat that like an import.

Also, in `tsconfig.json` you can specify a `types` field which sort of implicitly imports those types into every file, e.g.

```
"types": ["node", "jest"]
```

Creates dependencies on `@types/node` and `@types/jest`

Example implementation:

```
const requirePackageName = require('require-package-name');

const tsconfigParser: Parser = (filePath, deps, rootDir) => {
  const content = readFileSync(filePath, {encoding: 'utf8'});
  const foundDeps: string[] = [];
  const tsconfigJson = JSON.parse(content);
  const types = tsconfigJson.compilerOptions?.types;
  if (types) {
    for (const pkg of types) {
      foundDeps.push(`@types/${pkg}`);
    }
  }
  if (tsconfigJson.extends) {
    foundDeps.push(tsconfigJson.extends);
  }
  return foundDeps.map(p => requirePackageName(p)).filter(Boolean);
};

```

**Comment by dobesv** [comment]
not stale

**Comment by BenJackGill** [comment]
+1 for this feature.

I have a monorepo made with `turborepo` and it uses the "extends" pattern a lot.

This would fix this false positive.
