### ISSUE TITLE
Detect babel config in package.json

### ISSUE THREAD

**Issue by dobesv** [depcheck/depcheck#721]
Babel configuration can be placed into `package.json`, e.g.

```
"babel": {
   "presets": ["@foo/bar"]
}
```

In this case `@foo/bar` should be considered a dependency.

**Comment by khaing211** [comment]
There is eslint and prettier config in `package.json`. I hope this issue covers that.

**Comment by dobesv** [comment]
> There is eslint and prettier config in `package.json`. I hope this issue covers that.

This issue only refers to babel, probably safer to open separate issues for those ones.
