### ISSUE TITLE
255 exit code is confusing

### ISSUE THREAD

**Issue by supalarry** [depcheck/depcheck#736]
### Feature request description

Handle missing "invalidFiles" and "invalidDirs" differently than dependency issues.

### Example

If I run `pnpm depcheck` and I have unused dependencies BUT THERE ARE NO invalid files or dirs, I get a message
```
 ELIFECYCLE  Command failed with exit code 255.
```

However, if there are invalid files or dirs (as can be seen with the `--json` flag), the message is the same:
```
 ELIFECYCLE  Command failed with exit code 255.
```

Unless the problem is on my end, this is confusing. How are developers supposed to know when to use `--json` flag to check if there are "invalidFiles" or "invalidDirs"?

### Versions

- `node -v`: v16.15.1
- `npm -v`: I do not use npm. I use pnpm at 7.1.9
- `depcheck --version`: 1.4.3

**Comment by nocive** [comment]
We started seeing weird exit codes with node 16.15 as well, in our case it was exit code 243.
Rolling back to node 16.14 fixed the issue for us.
