### ISSUE TITLE
 Flag to make logs readable and less verbose

### ISSUE THREAD

**Issue by Pablogot** [depcheck/depcheck#759]
Description:
Reading the logs generated by dep check is very time-consuming, I am personally not interested in seeing hundreds of lines of  `YN0000: [@package]: No depcheck issue` to find an unused dependency.
Removing the verbose flag doesn't help either since it wouldn't display the dependency that actually has an issue and will still log hundreds of lines of `No depcheck issue`.

it would be more useful to remove the log for  `No depcheck issue` all together  when removing the `--verbose` flag.

My project is huge and this would really help.

**Comment by rumpl** [comment]
> I am personally not interested in seeing hundreds of lines of `YN0000: [@package]: No depcheck issue`

How are you getting hundreds of lines of logs? This messaege is printed once when you run `depcheck`. Are you running it hundreds of times?

**Comment by seansfkelley** [comment]
I can't speak for the original poster, but I have upwards of 100 packages in my monorepo, so for me, yes.

**Comment by openam** [comment]
Also no OP, but I'm using lerna to execute `depcheck` against 100+ packages in a monorepo as well.
