### ISSUE TITLE
Missing = Using

### ISSUE THREAD

**Issue by sequencerr** [depcheck/depcheck#794]
### Bug Description

A description of the bug

### Code snippets

Where the dependency is used:

```
code snippet here
```

Where the dependency is listed in package.json:

```
package.json snippet here
please include the section name (e.g. devDependencies, dependencies)
	"dependencies": {
		"@sentry/node": "^7.21.1",
		"@sentry/tracing": "^7.21.1",
		"aws-sdk": "^2.1354.0",
		"bcryptjs": "^2.4.3",
		"body-parser": "^1.20.0",
		"bull": "^4.10.1",
		"bull-arena": "^3.30.0",
		"compression": "^1.7.4",
		"cookie-parser": "^1.4.6",
		"cors": "^2.8.5",
		"dotenv": "^16.0.1",
		"express": "^4.18.1",
		"express-validator": "^7.0.1",
		"forever": "^4.0.3",
		"jsonwebtoken": "^9.0.0",
		"milliseconds": "^1.0.3",
		"node-fetch": "^3.2.10",
		"node-telegram-bot-api": "^0.61.0",
		"nodemailer": "^6.7.7",
		"nunjucks": "^3.2.3",
		"pg": "^8.8.0",
		"qs-stringify": "^1.2.1",
		"random-useragent": "^0.5.0",
		"sequelize": "^6.25.2"
	},
	"devDependencies": {
		"@babel/core": "^7.21.4",
		"@babel/eslint-parser": "^7.21.3",
		"@getify/eslint-plugin-proper-ternary": "^3.1.1",
		"@types/node": "^18.16.0",
		"depcheck": "^1.4.3",
		"eslint": "^8.39.0",
		"eslint-config-prettier": "^8.8.0",
		"eslint-plugin-etc": "^2.0.2",
		"eslint-plugin-import": "^2.23.4",
		"eslint-plugin-prettier": "^4.2.1",
		"husky": "^8.0.3",
		"lint-staged": "^13.2.2",
		"prettier": "^2.3.2",
		"prettier-plugin-jsdoc": "^0.4.2",
		"prettier-plugin-organize-imports": "^3.2.2",
		"typescript": "^5.0.4"
	}
```

### Versions

- `node -v`:
- `npm -v`:
- `depcheck --version`:

v18.14.0
9.3.1
1.4.3

### Extra info
![image](https://user-images.githubusercontent.com/45060278/234836941-80664b4b-e735-47ea-a675-38e28e473355.png)

Any extra info you want to include. Thank you for the bug report!

BONUS POINTS: If you wish to help us debug further, the `depcheck --json` option will show more information. Check [here in the README](https://github.com/depcheck/depcheck#example) for documentation on json output.

**Comment by sequencerr** [comment]
@TheSonOfThomp it's closed as not planned.

**Comment by TheSonOfThomp** [comment]
Got it. That changelog was confusing

**Comment by sequencerr** [comment]
lol idk why they did include this

**Comment by rumpl** [comment]
> lol idk why they did include this

The changelogs are automatically generated by a script, looks like it hit a bug

**Comment by rumpl** [comment]
There, I fixed it
