### ISSUE TITLE
Bug with subdirectories?

### ISSUE THREAD

**Issue by smazurov** [depcheck/depcheck#81]
I'm running into an issue where files in subdirectories aren't correctly checked (at least for `peerDependancies`) for `require` statements

### Quick test:
**./package.json** and `npm install`
```json
{
  "name": "test-dep",
  "version": "1.0.0",
  "description": "test peerdeps",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "css-modules-require-hook": "^2.1.0",
    "postcss-modules-extract-imports": "^1.0.0",
    "postcss-modules-local-by-default": "^1.0.0",
    "postcss-modules-scope": "^1.0.0",
    "postcss-modules-values": "^1.1.1"
  }
}
```

**./entry.js**
```js
require('css-modules-require-hook');
```

Running `depcheck`:
> No unused dependencies

_Working as intended_

### Breaks:

make a folder `test/` and move `entry.js` there:
```
$ mkdir test && mv entry.js test
```

Running `depcheck`:

> Unused devDependencies
> * postcss-modules-extract-imports
> * postcss-modules-local-by-default
> * postcss-modules-scope
> * postcss-modules-values

---------

Debug info:
```
$ npm --version
3.3.12
$ node --version
v5.1.0
```
depcheck is latest installed with `npm install -g depcheck`

-----

Is this desired behavior? Quick look at the folder scanning, it seems to be going into (sub)directories unless they're ignored.

**Comment by lijunle** [comment]
Confirmed as a bug, It is caused by `subdir` is passed to `checkDirectory` by mistake ([code](https://github.com/depcheck/depcheck/blob/master/src/index.js#L161)), should be (root) `dir`.

**Comment by lijunle** [comment]
Release [0.5.11](https://github.com/depcheck/depcheck/releases/tag/0.5.11) to fix this.

**Comment by smazurov** [comment]
Thanks a ton, this is an awesome tool (I use it with `npm-check`), thank you for maintaining it.
