### ISSUE TITLE
tsconfig is parsed as json not jsonc

### ISSUE THREAD

**Issue by AlexAegis** [depcheck/depcheck#811]
### Bug Description

Having a comment in a tsconfig file does not bother tsc as it's treated as jsonc

```jsonc
// a comment
{
	"$schema": "https://json.schemastore.org/tsconfig",
	"compilerOptions": {
		"outDir": "./dist/out-tsc"
	}
}
```

However depcheck reads it as json and fails parsing it.

### Versions

- `depcheck --version`: 1.4.3

### Extra info

From depcheck --json:

	"invalidFiles": {
		"/home/alex/git/@aa/autolib/packages/vite-plugin-autolib/tsconfig.json": "SyntaxError: /home/alex/git/@aa/autolib/packages/vite-plugin-autolib/tsconfig.json: Unexpected token '/', \"// autogen\"... is not valid JSON\n    at parse (<anonymous>)\n    at Module._extensions..json (node:internal/modules/cjs/loader:1324:39)\n    at Module.load (node:internal/modules/cjs/loader:1113:32)\n    at Module._load (node:internal/modules/cjs/loader:960:12)\n    at Module.require (node:internal/modules/cjs/loader:1137:19)\n    at require (node:internal/modules/helpers:121:18)\n    at readJSON (/home/alex/git/@aa/autolib/node_modules/.pnpm/depcheck@1.4.3/node_modules/depcheck/dist/utils/index.js:28:10)\n    at parseTTypeScript (/home/alex/git/@aa/autolib/node_modules/.pnpm/depcheck@1.4.3/node_modules/depcheck/dist/special/ttypescript.js:23:41)\n    at getDependencies (/home/alex/git/@aa/autolib/node_modules/.pnpm/depcheck@1.4.3/node_modules/depcheck/dist/check.js:71:24)\n    at /home/alex/git/@aa/autolib/node_modules/.pnpm/depcheck@1.4.3/node_modules/depcheck/dist/check.js:97:32",
		"/home/alex/git/@aa/autolib/packages/vite-plugin-autolib/src/internal/autolib.plugin.ts": "SyntaxError: Missing semicolon. (140:2)\n    at Parser._raise (/home/alex/git/@aa/autolib/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:541:17)\n    at Parser.raiseWithData (/home/alex/git/@aa/autolib/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:534:17)\n    at Parser.raise (/home/alex/git/@aa/autolib/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:495:17)\n    at Parser.semicolon (/home/alex/git/@aa/autolib/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:3550:10)\n    at Parser.parseVarStatement (/home/alex/git/@aa/autolib/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:13837:10)\n    at Parser.parseStatementContent (/home/alex/git/@aa/autolib/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:13421:21)\n    at Parser.parseStatementContent (/home/alex/git/@aa/autolib/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:9528:18)\n    at Parser.parseStatement (/home/alex/git/@aa/autolib/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:13352:17)\n    at Parser.parseBlockOrModuleBlockBody (/home/alex/git/@aa/autolib/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:13941:25)\n    at Parser.parseBlockBody (/home/alex/git/@aa/autolib/node_modules/.pnpm/@babel+parser@7.16.4/node_modules/@babel/parser/lib/index.js:13932:10)"
	},

**Comment by znarf** [comment]
Fixed in https://github.com/depcheck/depcheck/pull/806

**Comment by znarf** [comment]
Fixed in https://github.com/depcheck/depcheck/pull/826
