### ISSUE TITLE
Dev dependencies such as Mocha, Gatsby are falsely labelled as unused

### ISSUE THREAD

**Issue by NimmiW** [depcheck/depcheck#822]
### Bug Description

A lot of false positives, especially for Dev dependencies, are observed.

### Code snippets for replicating the bug

Clone the following repo
[mihneadb/node-directory-tree](https://github.com/mihneadb/node-directory-tree)

```
> git clone https://github.com/mihneadb/node-directory-tree.git
```

Checkout to commit sha=`c3c2d688df631a11cee4a7564320fcbfdd704662`
```
> git checkout c3c2d688df631a11cee4a7564320fcbfdd704662
```

Where the dependency is listed in package.json:

```
 "devDependencies": {
        ...
    "mocha": "^10.2.0",
        ...
  }
```

Run depcheck with mocha defined as a special case
```
> npx depcheck --specials=mocha
Unused dependencies
* command-line-args
* command-line-usage
Unused devDependencies
* mocha
* typescript
```

`mocha` is listed as an unused dependency, but if you run a grep search (`grep -r "mocha" .`), you would see that `package.json` have    `"test": "mocha"`. This means mocha has been used somewhere in the project (at least for testing). Please take a look below for where the dependency is used.

```
 "scripts": {
    "test": "mocha",
       ...
  }
```

### Versions

```
> node -v
v16.15.0
> npm -v
9.8.1
> depcheck --version
1.4.3
```

### Extra info

The details about my computer are shown below:
<img width="213" alt="image" src="https://github.com/depcheck/depcheck/assets/26009680/9fc0e870-a4ba-4a8f-a23c-a8911c0cf3e4">

Thanks for looking into this issue! Any help to avoid these false positives would be appreciated!

**Comment by znarf** [comment]
`mocha` and `typescript` are not reported with the latest version of depcheck (1.4.7)
