### ISSUE TITLE
Find dependencies which aren't listed in package.json

### ISSUE THREAD

**Issue by chrisbateman** [depcheck/depcheck#83]
I know it's kind of the inverse of what it does right now, but I was just wondering if you'd be open to having this kind of functionality added to depcheck.

There is a separate tool that already does this (dependency-check), but it doesn't support ES6 syntax yet. Depcheck may have better infrastructure ready to cover both cases.

And by the way - this is a great tool, thanks for all your work on it.

**Comment by lijunle** [comment]
Yes, I wanna implement it. That is tracked by #41. I am open for a PR. However, I am on vacation, will have a look and continue on it after back work.

**Comment by lijunle** [comment]
Closed by #90
