### ISSUE TITLE
doesn't work with CSS dependencies

### ISSUE THREAD

**Issue by daviestar** [depcheck/depcheck#99]
package.json:
```json
"dependencies": {
  "bootstrap-sass": "^3.3.6",
  "font-awesome": "^4.5.0",
}
```
styles.scss:
```css
@import "node_modules/bootstrap-sass/assets/stylesheets/bootstrap";
@import "node_modules/font-awesome/scss/font-awesome.scss";
```
depcheck:
```
Unused Dependencies
* bootstrap-sass
* font-awesome
```

**Comment by lijunle** [comment]
Thanks for reporting. This should be a feature.

**Comment by daviestar** [comment]
Great, depcheck saved me a lot of time today, thankyou :+1:

**Comment by lijunle** [comment]
@daviestar Do you want to take a look on the PR #113?

The depcheck declare `node-sass` as peer dependency.

- When you use depcheck as global package, install node-sass as global package.
- When install depcheck as project dev dependency, install node-sass as dev dependency too.

Do you think this is OK?
